/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  Access,
  EmptyClaim,
  Error,
  IdleRefusal,
  Lease,
  Node,
  Operation,
  PostInternalV1AccessBody,
  PostInternalV1AdmissionsBody,
  PostInternalV1ControllerLeaseAcquireBody,
  PostInternalV1ControllerLeaseReleaseBody,
  PostInternalV1ControllerLeaseRenewBody,
  PostInternalV1NodesIdleBody,
  PostInternalV1NodesRegisterBody,
  PostInternalV1NodesStatusBody,
  PostInternalV1NodesTicketsTicketFinishBody,
  PostInternalV1OperationsClaimBody,
  PostInternalV1OperationsOidAdvanceBody,
  PostInternalV1OperationsOidDeferBody,
  PostInternalV1OperationsOidEffects200,
  PostInternalV1OperationsOidEffectsBody,
  PostInternalV1OperationsOidEffectsEidResult200,
  PostInternalV1OperationsOidEffectsEidResultBody,
  PostInternalV1OperationsOidSnapshotBody,
  Snapshot,
  Ticket
} from '../generated.schemas';

import { customInstance } from '../../lib/api-client';
import type { ErrorType } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Checks final user, active tenant membership and tenant scope. Execute additionally requires current controller lease epoch, open admission, ready workspace and a fresh initialized Node. This lookup is not an execution reservation; use admissions.
 * @summary access
 */
export const postInternalV1Access = (
    postInternalV1AccessBody: PostInternalV1AccessBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Access>(
      {url: `/internal/v1/access`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postInternalV1AccessBody, signal
    },
      options);
    }




export const getPostInternalV1AccessMutationKey = () => ['postInternalV1Access'] as const;

export const getPostInternalV1AccessMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1Access>>, TError,PostInternalV1AccessMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postInternalV1Access>>, TError,PostInternalV1AccessMutationVariables, TContext> => {

const mutationKey = getPostInternalV1AccessMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postInternalV1Access>>, PostInternalV1AccessMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postInternalV1Access(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostInternalV1AccessMutationResult = NonNullable<Awaited<ReturnType<typeof postInternalV1Access>>>
    export type PostInternalV1AccessMutationBody = PostInternalV1AccessBody
    export type PostInternalV1AccessMutationError = ErrorType<Error>
    export type PostInternalV1AccessMutationVariables = {data: PostInternalV1AccessBody}

    /**
 * @summary access
 */
export const usePostInternalV1Access = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1Access>>, TError,PostInternalV1AccessMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postInternalV1Access>>,
        TError,
        PostInternalV1AccessMutationVariables,
        TContext
      > => {
      return useMutation(getPostInternalV1AccessMutationOptions(options), queryClient);
    }
    /**
 * Atomically reserves an active task/interaction ticket on the current Node under the same transaction lock as stop/delete. Requires current controller holder+epoch and caller-bound final-user token. Unknown/uncompleted tickets remain active; bound Node explicitly finishes them. Repeated ticket UUID with identical scope returns it while admission remains open.
 * @summary admit
 */
export const postInternalV1Admissions = (
    postInternalV1AdmissionsBody: PostInternalV1AdmissionsBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Ticket>(
      {url: `/internal/v1/admissions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postInternalV1AdmissionsBody, signal
    },
      options);
    }




export const getPostInternalV1AdmissionsMutationKey = () => ['postInternalV1Admissions'] as const;

export const getPostInternalV1AdmissionsMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1Admissions>>, TError,PostInternalV1AdmissionsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postInternalV1Admissions>>, TError,PostInternalV1AdmissionsMutationVariables, TContext> => {

const mutationKey = getPostInternalV1AdmissionsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postInternalV1Admissions>>, PostInternalV1AdmissionsMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postInternalV1Admissions(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostInternalV1AdmissionsMutationResult = NonNullable<Awaited<ReturnType<typeof postInternalV1Admissions>>>
    export type PostInternalV1AdmissionsMutationBody = PostInternalV1AdmissionsBody
    export type PostInternalV1AdmissionsMutationError = ErrorType<Error>
    export type PostInternalV1AdmissionsMutationVariables = {data: PostInternalV1AdmissionsBody}

    /**
 * @summary admit
 */
export const usePostInternalV1Admissions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1Admissions>>, TError,PostInternalV1AdmissionsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postInternalV1Admissions>>,
        TError,
        PostInternalV1AdmissionsMutationVariables,
        TContext
      > => {
      return useMutation(getPostInternalV1AdmissionsMutationOptions(options), queryClient);
    }
    /**
 * Controller subject is holderId. Global lease lasts 30 seconds using PostgreSQL clock_timestamp(); renew every 10 seconds. Expired acquisition increments epoch, active same-holder acquisition returns current lease. Release and renew require exact live holder+epoch.
 * @summary lease acquire
 */
export const postInternalV1ControllerLeaseAcquire = (
    postInternalV1ControllerLeaseAcquireBody: PostInternalV1ControllerLeaseAcquireBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Lease>(
      {url: `/internal/v1/controller-lease/acquire`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postInternalV1ControllerLeaseAcquireBody, signal
    },
      options);
    }




export const getPostInternalV1ControllerLeaseAcquireMutationKey = () => ['postInternalV1ControllerLeaseAcquire'] as const;

export const getPostInternalV1ControllerLeaseAcquireMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1ControllerLeaseAcquire>>, TError,PostInternalV1ControllerLeaseAcquireMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postInternalV1ControllerLeaseAcquire>>, TError,PostInternalV1ControllerLeaseAcquireMutationVariables, TContext> => {

const mutationKey = getPostInternalV1ControllerLeaseAcquireMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postInternalV1ControllerLeaseAcquire>>, PostInternalV1ControllerLeaseAcquireMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postInternalV1ControllerLeaseAcquire(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostInternalV1ControllerLeaseAcquireMutationResult = NonNullable<Awaited<ReturnType<typeof postInternalV1ControllerLeaseAcquire>>>
    export type PostInternalV1ControllerLeaseAcquireMutationBody = PostInternalV1ControllerLeaseAcquireBody
    export type PostInternalV1ControllerLeaseAcquireMutationError = ErrorType<Error>
    export type PostInternalV1ControllerLeaseAcquireMutationVariables = {data: PostInternalV1ControllerLeaseAcquireBody}

    /**
 * @summary lease acquire
 */
export const usePostInternalV1ControllerLeaseAcquire = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1ControllerLeaseAcquire>>, TError,PostInternalV1ControllerLeaseAcquireMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postInternalV1ControllerLeaseAcquire>>,
        TError,
        PostInternalV1ControllerLeaseAcquireMutationVariables,
        TContext
      > => {
      return useMutation(getPostInternalV1ControllerLeaseAcquireMutationOptions(options), queryClient);
    }
    /**
 * Controller subject is holderId. Global lease lasts 30 seconds using PostgreSQL clock_timestamp(); renew every 10 seconds. Expired acquisition increments epoch, active same-holder acquisition returns current lease. Release and renew require exact live holder+epoch.
 * @summary lease release
 */
export const postInternalV1ControllerLeaseRelease = (
    postInternalV1ControllerLeaseReleaseBody: PostInternalV1ControllerLeaseReleaseBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Lease>(
      {url: `/internal/v1/controller-lease/release`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postInternalV1ControllerLeaseReleaseBody, signal
    },
      options);
    }




export const getPostInternalV1ControllerLeaseReleaseMutationKey = () => ['postInternalV1ControllerLeaseRelease'] as const;

export const getPostInternalV1ControllerLeaseReleaseMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1ControllerLeaseRelease>>, TError,PostInternalV1ControllerLeaseReleaseMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postInternalV1ControllerLeaseRelease>>, TError,PostInternalV1ControllerLeaseReleaseMutationVariables, TContext> => {

const mutationKey = getPostInternalV1ControllerLeaseReleaseMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postInternalV1ControllerLeaseRelease>>, PostInternalV1ControllerLeaseReleaseMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postInternalV1ControllerLeaseRelease(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostInternalV1ControllerLeaseReleaseMutationResult = NonNullable<Awaited<ReturnType<typeof postInternalV1ControllerLeaseRelease>>>
    export type PostInternalV1ControllerLeaseReleaseMutationBody = PostInternalV1ControllerLeaseReleaseBody
    export type PostInternalV1ControllerLeaseReleaseMutationError = ErrorType<Error>
    export type PostInternalV1ControllerLeaseReleaseMutationVariables = {data: PostInternalV1ControllerLeaseReleaseBody}

    /**
 * @summary lease release
 */
export const usePostInternalV1ControllerLeaseRelease = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1ControllerLeaseRelease>>, TError,PostInternalV1ControllerLeaseReleaseMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postInternalV1ControllerLeaseRelease>>,
        TError,
        PostInternalV1ControllerLeaseReleaseMutationVariables,
        TContext
      > => {
      return useMutation(getPostInternalV1ControllerLeaseReleaseMutationOptions(options), queryClient);
    }
    /**
 * Controller subject is holderId. Global lease lasts 30 seconds using PostgreSQL clock_timestamp(); renew every 10 seconds. Expired acquisition increments epoch, active same-holder acquisition returns current lease. Release and renew require exact live holder+epoch.
 * @summary lease renew
 */
export const postInternalV1ControllerLeaseRenew = (
    postInternalV1ControllerLeaseRenewBody: PostInternalV1ControllerLeaseRenewBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Lease>(
      {url: `/internal/v1/controller-lease/renew`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postInternalV1ControllerLeaseRenewBody, signal
    },
      options);
    }




export const getPostInternalV1ControllerLeaseRenewMutationKey = () => ['postInternalV1ControllerLeaseRenew'] as const;

export const getPostInternalV1ControllerLeaseRenewMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1ControllerLeaseRenew>>, TError,PostInternalV1ControllerLeaseRenewMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postInternalV1ControllerLeaseRenew>>, TError,PostInternalV1ControllerLeaseRenewMutationVariables, TContext> => {

const mutationKey = getPostInternalV1ControllerLeaseRenewMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postInternalV1ControllerLeaseRenew>>, PostInternalV1ControllerLeaseRenewMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postInternalV1ControllerLeaseRenew(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostInternalV1ControllerLeaseRenewMutationResult = NonNullable<Awaited<ReturnType<typeof postInternalV1ControllerLeaseRenew>>>
    export type PostInternalV1ControllerLeaseRenewMutationBody = PostInternalV1ControllerLeaseRenewBody
    export type PostInternalV1ControllerLeaseRenewMutationError = ErrorType<Error>
    export type PostInternalV1ControllerLeaseRenewMutationVariables = {data: PostInternalV1ControllerLeaseRenewBody}

    /**
 * @summary lease renew
 */
export const usePostInternalV1ControllerLeaseRenew = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1ControllerLeaseRenew>>, TError,PostInternalV1ControllerLeaseRenewMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postInternalV1ControllerLeaseRenew>>,
        TError,
        PostInternalV1ControllerLeaseRenewMutationVariables,
        TContext
      > => {
      return useMutation(getPostInternalV1ControllerLeaseRenewMutationOptions(options), queryClient);
    }
    /**
 * Requires node service credential whose sub is a process UUID and whose workspaceId/sandboxId/generation match the current unterminated instance. Node identity cannot be replaced while live. Status/idle use Node version; ticket finish uses Ticket version and a completed replay is idempotent. initialized cannot regress. Idle is scoped to operationId and exact Workspace admissionEpoch; true requires no active tickets. false fails that quiesce operation with resource_in_use and restores original admission. Registration requires protocolVersion=1; Pod Running alone cannot make Ready.
 * @summary node idle
 */
export const postInternalV1NodesIdle = (
    postInternalV1NodesIdleBody: PostInternalV1NodesIdleBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Node | IdleRefusal>(
      {url: `/internal/v1/nodes/idle`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postInternalV1NodesIdleBody, signal
    },
      options);
    }




export const getPostInternalV1NodesIdleMutationKey = () => ['postInternalV1NodesIdle'] as const;

export const getPostInternalV1NodesIdleMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1NodesIdle>>, TError,PostInternalV1NodesIdleMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postInternalV1NodesIdle>>, TError,PostInternalV1NodesIdleMutationVariables, TContext> => {

const mutationKey = getPostInternalV1NodesIdleMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postInternalV1NodesIdle>>, PostInternalV1NodesIdleMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postInternalV1NodesIdle(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostInternalV1NodesIdleMutationResult = NonNullable<Awaited<ReturnType<typeof postInternalV1NodesIdle>>>
    export type PostInternalV1NodesIdleMutationBody = PostInternalV1NodesIdleBody
    export type PostInternalV1NodesIdleMutationError = ErrorType<Error>
    export type PostInternalV1NodesIdleMutationVariables = {data: PostInternalV1NodesIdleBody}

    /**
 * @summary node idle
 */
export const usePostInternalV1NodesIdle = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1NodesIdle>>, TError,PostInternalV1NodesIdleMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postInternalV1NodesIdle>>,
        TError,
        PostInternalV1NodesIdleMutationVariables,
        TContext
      > => {
      return useMutation(getPostInternalV1NodesIdleMutationOptions(options), queryClient);
    }
    /**
 * Requires node service credential whose sub is a process UUID and whose workspaceId/sandboxId/generation match the current unterminated instance. Node identity cannot be replaced while live. Status/idle use Node version; ticket finish uses Ticket version and a completed replay is idempotent. initialized cannot regress. Idle is scoped to operationId and exact Workspace admissionEpoch; true requires no active tickets. false fails that quiesce operation with resource_in_use and restores original admission. Registration requires protocolVersion=1; Pod Running alone cannot make Ready.
 * @summary node register
 */
export const postInternalV1NodesRegister = (
    postInternalV1NodesRegisterBody: PostInternalV1NodesRegisterBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Node>(
      {url: `/internal/v1/nodes/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postInternalV1NodesRegisterBody, signal
    },
      options);
    }




export const getPostInternalV1NodesRegisterMutationKey = () => ['postInternalV1NodesRegister'] as const;

export const getPostInternalV1NodesRegisterMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1NodesRegister>>, TError,PostInternalV1NodesRegisterMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postInternalV1NodesRegister>>, TError,PostInternalV1NodesRegisterMutationVariables, TContext> => {

const mutationKey = getPostInternalV1NodesRegisterMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postInternalV1NodesRegister>>, PostInternalV1NodesRegisterMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postInternalV1NodesRegister(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostInternalV1NodesRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postInternalV1NodesRegister>>>
    export type PostInternalV1NodesRegisterMutationBody = PostInternalV1NodesRegisterBody
    export type PostInternalV1NodesRegisterMutationError = ErrorType<Error>
    export type PostInternalV1NodesRegisterMutationVariables = {data: PostInternalV1NodesRegisterBody}

    /**
 * @summary node register
 */
export const usePostInternalV1NodesRegister = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1NodesRegister>>, TError,PostInternalV1NodesRegisterMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postInternalV1NodesRegister>>,
        TError,
        PostInternalV1NodesRegisterMutationVariables,
        TContext
      > => {
      return useMutation(getPostInternalV1NodesRegisterMutationOptions(options), queryClient);
    }
    /**
 * Requires node service credential whose sub is a process UUID and whose workspaceId/sandboxId/generation match the current unterminated instance. Node identity cannot be replaced while live. Status/idle use Node version; ticket finish uses Ticket version and a completed replay is idempotent. initialized cannot regress. Idle is scoped to operationId and exact Workspace admissionEpoch; true requires no active tickets. false fails that quiesce operation with resource_in_use and restores original admission. Registration requires protocolVersion=1; Pod Running alone cannot make Ready.
 * @summary node status
 */
export const postInternalV1NodesStatus = (
    postInternalV1NodesStatusBody: PostInternalV1NodesStatusBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Node>(
      {url: `/internal/v1/nodes/status`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postInternalV1NodesStatusBody, signal
    },
      options);
    }




export const getPostInternalV1NodesStatusMutationKey = () => ['postInternalV1NodesStatus'] as const;

export const getPostInternalV1NodesStatusMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1NodesStatus>>, TError,PostInternalV1NodesStatusMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postInternalV1NodesStatus>>, TError,PostInternalV1NodesStatusMutationVariables, TContext> => {

const mutationKey = getPostInternalV1NodesStatusMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postInternalV1NodesStatus>>, PostInternalV1NodesStatusMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postInternalV1NodesStatus(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostInternalV1NodesStatusMutationResult = NonNullable<Awaited<ReturnType<typeof postInternalV1NodesStatus>>>
    export type PostInternalV1NodesStatusMutationBody = PostInternalV1NodesStatusBody
    export type PostInternalV1NodesStatusMutationError = ErrorType<Error>
    export type PostInternalV1NodesStatusMutationVariables = {data: PostInternalV1NodesStatusBody}

    /**
 * @summary node status
 */
export const usePostInternalV1NodesStatus = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1NodesStatus>>, TError,PostInternalV1NodesStatusMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postInternalV1NodesStatus>>,
        TError,
        PostInternalV1NodesStatusMutationVariables,
        TContext
      > => {
      return useMutation(getPostInternalV1NodesStatusMutationOptions(options), queryClient);
    }
    /**
 * Requires node service credential whose sub is a process UUID and whose workspaceId/sandboxId/generation match the current unterminated instance. Node identity cannot be replaced while live. Status/idle use Node version; ticket finish uses Ticket version and a completed replay is idempotent. initialized cannot regress. Idle is scoped to operationId and exact Workspace admissionEpoch; true requires no active tickets. false fails that quiesce operation with resource_in_use and restores original admission. Registration requires protocolVersion=1; Pod Running alone cannot make Ready.
 * @summary node finish
 */
export const postInternalV1NodesTicketsTicketFinish = (
    ticket: string,
    postInternalV1NodesTicketsTicketFinishBody: PostInternalV1NodesTicketsTicketFinishBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Ticket>(
      {url: `/internal/v1/nodes/tickets/${ticket}/finish`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postInternalV1NodesTicketsTicketFinishBody, signal
    },
      options);
    }




export const getPostInternalV1NodesTicketsTicketFinishMutationKey = () => ['postInternalV1NodesTicketsTicketFinish'] as const;

export const getPostInternalV1NodesTicketsTicketFinishMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1NodesTicketsTicketFinish>>, TError,PostInternalV1NodesTicketsTicketFinishMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postInternalV1NodesTicketsTicketFinish>>, TError,PostInternalV1NodesTicketsTicketFinishMutationVariables, TContext> => {

const mutationKey = getPostInternalV1NodesTicketsTicketFinishMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postInternalV1NodesTicketsTicketFinish>>, PostInternalV1NodesTicketsTicketFinishMutationVariables> = (props) => {
          const {ticket,data} = props ?? {};

          return  postInternalV1NodesTicketsTicketFinish(ticket,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostInternalV1NodesTicketsTicketFinishMutationResult = NonNullable<Awaited<ReturnType<typeof postInternalV1NodesTicketsTicketFinish>>>
    export type PostInternalV1NodesTicketsTicketFinishMutationBody = PostInternalV1NodesTicketsTicketFinishBody
    export type PostInternalV1NodesTicketsTicketFinishMutationError = ErrorType<Error>
    export type PostInternalV1NodesTicketsTicketFinishMutationVariables = {ticket: string;data: PostInternalV1NodesTicketsTicketFinishBody}

    /**
 * @summary node finish
 */
export const usePostInternalV1NodesTicketsTicketFinish = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1NodesTicketsTicketFinish>>, TError,PostInternalV1NodesTicketsTicketFinishMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postInternalV1NodesTicketsTicketFinish>>,
        TError,
        PostInternalV1NodesTicketsTicketFinishMutationVariables,
        TContext
      > => {
      return useMutation(getPostInternalV1NodesTicketsTicketFinishMutationOptions(options), queryClient);
    }
    /**
 * Controller requests require an independent controller service credential; holder, active database-time lease epoch and operation version are checked. Claims queued/due retry/any running operation; reclaiming with the same epoch increments the operation version and fences stale in-memory workers. Returns a full scoped recovery snapshot. Reconcile every existing effect with Substrate by stable ID before planning or advancing. No automatic prompt replay.
 * @summary claim
 */
export const postInternalV1OperationsClaim = (
    postInternalV1OperationsClaimBody: PostInternalV1OperationsClaimBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Snapshot | EmptyClaim>(
      {url: `/internal/v1/operations/claim`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postInternalV1OperationsClaimBody, signal
    },
      options);
    }




export const getPostInternalV1OperationsClaimMutationKey = () => ['postInternalV1OperationsClaim'] as const;

export const getPostInternalV1OperationsClaimMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1OperationsClaim>>, TError,PostInternalV1OperationsClaimMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postInternalV1OperationsClaim>>, TError,PostInternalV1OperationsClaimMutationVariables, TContext> => {

const mutationKey = getPostInternalV1OperationsClaimMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postInternalV1OperationsClaim>>, PostInternalV1OperationsClaimMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postInternalV1OperationsClaim(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostInternalV1OperationsClaimMutationResult = NonNullable<Awaited<ReturnType<typeof postInternalV1OperationsClaim>>>
    export type PostInternalV1OperationsClaimMutationBody = PostInternalV1OperationsClaimBody
    export type PostInternalV1OperationsClaimMutationError = ErrorType<Error>
    export type PostInternalV1OperationsClaimMutationVariables = {data: PostInternalV1OperationsClaimBody}

    /**
 * @summary claim
 */
export const usePostInternalV1OperationsClaim = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1OperationsClaim>>, TError,PostInternalV1OperationsClaimMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postInternalV1OperationsClaim>>,
        TError,
        PostInternalV1OperationsClaimMutationVariables,
        TContext
      > => {
      return useMutation(getPostInternalV1OperationsClaimMutationOptions(options), queryClient);
    }
    /**
 * Controller requests require an independent controller service credential; holder, active database-time lease epoch and operation version are checked. Derives the next step server-side. Requires current-epoch successful effects. quiesce requires all tickets finished and fresh exact-epoch idle proof from each live Node. node step atomically commits worktree readiness, Workspace Ready/admission, and operation success after fresh initialized current Node. Cleanup and storage deletion cannot complete before termination confirmation.
 * @summary advance
 */
export const postInternalV1OperationsOidAdvance = (
    oid: string,
    postInternalV1OperationsOidAdvanceBody: PostInternalV1OperationsOidAdvanceBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Operation>(
      {url: `/internal/v1/operations/${oid}/advance`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postInternalV1OperationsOidAdvanceBody, signal
    },
      options);
    }




export const getPostInternalV1OperationsOidAdvanceMutationKey = () => ['postInternalV1OperationsOidAdvance'] as const;

export const getPostInternalV1OperationsOidAdvanceMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1OperationsOidAdvance>>, TError,PostInternalV1OperationsOidAdvanceMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postInternalV1OperationsOidAdvance>>, TError,PostInternalV1OperationsOidAdvanceMutationVariables, TContext> => {

const mutationKey = getPostInternalV1OperationsOidAdvanceMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postInternalV1OperationsOidAdvance>>, PostInternalV1OperationsOidAdvanceMutationVariables> = (props) => {
          const {oid,data} = props ?? {};

          return  postInternalV1OperationsOidAdvance(oid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostInternalV1OperationsOidAdvanceMutationResult = NonNullable<Awaited<ReturnType<typeof postInternalV1OperationsOidAdvance>>>
    export type PostInternalV1OperationsOidAdvanceMutationBody = PostInternalV1OperationsOidAdvanceBody
    export type PostInternalV1OperationsOidAdvanceMutationError = ErrorType<Error>
    export type PostInternalV1OperationsOidAdvanceMutationVariables = {oid: string;data: PostInternalV1OperationsOidAdvanceBody}

    /**
 * @summary advance
 */
export const usePostInternalV1OperationsOidAdvance = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1OperationsOidAdvance>>, TError,PostInternalV1OperationsOidAdvanceMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postInternalV1OperationsOidAdvance>>,
        TError,
        PostInternalV1OperationsOidAdvanceMutationVariables,
        TContext
      > => {
      return useMutation(getPostInternalV1OperationsOidAdvanceMutationOptions(options), queryClient);
    }
    /**
 * Controller requests require an independent controller service credential; holder, active database-time lease epoch and operation version are checked. Preserves operation/effect/resource references and current step; sets blocked or retry_wait with bounded retry delay. Never reports cleanup success on timeout.
 * @summary defer
 */
export const postInternalV1OperationsOidDefer = (
    oid: string,
    postInternalV1OperationsOidDeferBody: PostInternalV1OperationsOidDeferBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Operation>(
      {url: `/internal/v1/operations/${oid}/defer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postInternalV1OperationsOidDeferBody, signal
    },
      options);
    }




export const getPostInternalV1OperationsOidDeferMutationKey = () => ['postInternalV1OperationsOidDefer'] as const;

export const getPostInternalV1OperationsOidDeferMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1OperationsOidDefer>>, TError,PostInternalV1OperationsOidDeferMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postInternalV1OperationsOidDefer>>, TError,PostInternalV1OperationsOidDeferMutationVariables, TContext> => {

const mutationKey = getPostInternalV1OperationsOidDeferMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postInternalV1OperationsOidDefer>>, PostInternalV1OperationsOidDeferMutationVariables> = (props) => {
          const {oid,data} = props ?? {};

          return  postInternalV1OperationsOidDefer(oid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostInternalV1OperationsOidDeferMutationResult = NonNullable<Awaited<ReturnType<typeof postInternalV1OperationsOidDefer>>>
    export type PostInternalV1OperationsOidDeferMutationBody = PostInternalV1OperationsOidDeferBody
    export type PostInternalV1OperationsOidDeferMutationError = ErrorType<Error>
    export type PostInternalV1OperationsOidDeferMutationVariables = {oid: string;data: PostInternalV1OperationsOidDeferBody}

    /**
 * @summary defer
 */
export const usePostInternalV1OperationsOidDefer = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1OperationsOidDefer>>, TError,PostInternalV1OperationsOidDeferMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postInternalV1OperationsOidDefer>>,
        TError,
        PostInternalV1OperationsOidDeferMutationVariables,
        TContext
      > => {
      return useMutation(getPostInternalV1OperationsOidDeferMutationOptions(options), queryClient);
    }
    /**
 * Controller requests require an independent controller service credential; holder, active database-time lease epoch and operation version are checked. Only the effect kind appropriate to the current step is allowed. Scope is restricted to operation workspaces. Plan persists BEFORE dispatch; sandbox plan atomically increments generation and allocates a unique live instance. Old instance must be confirmed terminated. Same plan returns the same effect ID.
 * @summary plan
 */
export const postInternalV1OperationsOidEffects = (
    oid: string,
    postInternalV1OperationsOidEffectsBody: PostInternalV1OperationsOidEffectsBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostInternalV1OperationsOidEffects200>(
      {url: `/internal/v1/operations/${oid}/effects`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postInternalV1OperationsOidEffectsBody, signal
    },
      options);
    }




export const getPostInternalV1OperationsOidEffectsMutationKey = () => ['postInternalV1OperationsOidEffects'] as const;

export const getPostInternalV1OperationsOidEffectsMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1OperationsOidEffects>>, TError,PostInternalV1OperationsOidEffectsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postInternalV1OperationsOidEffects>>, TError,PostInternalV1OperationsOidEffectsMutationVariables, TContext> => {

const mutationKey = getPostInternalV1OperationsOidEffectsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postInternalV1OperationsOidEffects>>, PostInternalV1OperationsOidEffectsMutationVariables> = (props) => {
          const {oid,data} = props ?? {};

          return  postInternalV1OperationsOidEffects(oid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostInternalV1OperationsOidEffectsMutationResult = NonNullable<Awaited<ReturnType<typeof postInternalV1OperationsOidEffects>>>
    export type PostInternalV1OperationsOidEffectsMutationBody = PostInternalV1OperationsOidEffectsBody
    export type PostInternalV1OperationsOidEffectsMutationError = ErrorType<Error>
    export type PostInternalV1OperationsOidEffectsMutationVariables = {oid: string;data: PostInternalV1OperationsOidEffectsBody}

    /**
 * @summary plan
 */
export const usePostInternalV1OperationsOidEffects = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1OperationsOidEffects>>, TError,PostInternalV1OperationsOidEffectsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postInternalV1OperationsOidEffects>>,
        TError,
        PostInternalV1OperationsOidEffectsMutationVariables,
        TContext
      > => {
      return useMutation(getPostInternalV1OperationsOidEffectsMutationOptions(options), queryClient);
    }
    /**
 * Controller requests require an independent controller service credential; holder, active database-time lease epoch and operation version are checked. Reports/reconciles one scoped external effect. External ID cannot change; succeeded evidence is immutable. absent is allowed only for a planned effect. Worktree success requires real commitId and jobTerminated; cleanup requires removed and jobTerminated; termination requires terminated; storage requires layoutVersion=1; sandbox requires its preallocated instance ID. This endpoint trusts the authenticated controller's Substrate observation, not client-supplied status.
 * @summary effect result
 */
export const postInternalV1OperationsOidEffectsEidResult = (
    oid: string,
    eid: string,
    postInternalV1OperationsOidEffectsEidResultBody: PostInternalV1OperationsOidEffectsEidResultBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostInternalV1OperationsOidEffectsEidResult200>(
      {url: `/internal/v1/operations/${oid}/effects/${eid}/result`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postInternalV1OperationsOidEffectsEidResultBody, signal
    },
      options);
    }




export const getPostInternalV1OperationsOidEffectsEidResultMutationKey = () => ['postInternalV1OperationsOidEffectsEidResult'] as const;

export const getPostInternalV1OperationsOidEffectsEidResultMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1OperationsOidEffectsEidResult>>, TError,PostInternalV1OperationsOidEffectsEidResultMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postInternalV1OperationsOidEffectsEidResult>>, TError,PostInternalV1OperationsOidEffectsEidResultMutationVariables, TContext> => {

const mutationKey = getPostInternalV1OperationsOidEffectsEidResultMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postInternalV1OperationsOidEffectsEidResult>>, PostInternalV1OperationsOidEffectsEidResultMutationVariables> = (props) => {
          const {oid,eid,data} = props ?? {};

          return  postInternalV1OperationsOidEffectsEidResult(oid,eid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostInternalV1OperationsOidEffectsEidResultMutationResult = NonNullable<Awaited<ReturnType<typeof postInternalV1OperationsOidEffectsEidResult>>>
    export type PostInternalV1OperationsOidEffectsEidResultMutationBody = PostInternalV1OperationsOidEffectsEidResultBody
    export type PostInternalV1OperationsOidEffectsEidResultMutationError = ErrorType<Error>
    export type PostInternalV1OperationsOidEffectsEidResultMutationVariables = {oid: string;eid: string;data: PostInternalV1OperationsOidEffectsEidResultBody}

    /**
 * @summary effect result
 */
export const usePostInternalV1OperationsOidEffectsEidResult = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1OperationsOidEffectsEidResult>>, TError,PostInternalV1OperationsOidEffectsEidResultMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postInternalV1OperationsOidEffectsEidResult>>,
        TError,
        PostInternalV1OperationsOidEffectsEidResultMutationVariables,
        TContext
      > => {
      return useMutation(getPostInternalV1OperationsOidEffectsEidResultMutationOptions(options), queryClient);
    }
    /**
 * Controller requests require an independent controller service credential; holder, active database-time lease epoch and operation version are checked. Active tenant members may inspect project operations; administrative-stop remains administrator-only with a restricted projection. Retry only accepts blocked/retry_wait, exact operation version, and an idempotency key. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary snapshot
 */
export const postInternalV1OperationsOidSnapshot = (
    oid: string,
    postInternalV1OperationsOidSnapshotBody: PostInternalV1OperationsOidSnapshotBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Snapshot>(
      {url: `/internal/v1/operations/${oid}/snapshot`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postInternalV1OperationsOidSnapshotBody, signal
    },
      options);
    }




export const getPostInternalV1OperationsOidSnapshotMutationKey = () => ['postInternalV1OperationsOidSnapshot'] as const;

export const getPostInternalV1OperationsOidSnapshotMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1OperationsOidSnapshot>>, TError,PostInternalV1OperationsOidSnapshotMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postInternalV1OperationsOidSnapshot>>, TError,PostInternalV1OperationsOidSnapshotMutationVariables, TContext> => {

const mutationKey = getPostInternalV1OperationsOidSnapshotMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postInternalV1OperationsOidSnapshot>>, PostInternalV1OperationsOidSnapshotMutationVariables> = (props) => {
          const {oid,data} = props ?? {};

          return  postInternalV1OperationsOidSnapshot(oid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostInternalV1OperationsOidSnapshotMutationResult = NonNullable<Awaited<ReturnType<typeof postInternalV1OperationsOidSnapshot>>>
    export type PostInternalV1OperationsOidSnapshotMutationBody = PostInternalV1OperationsOidSnapshotBody
    export type PostInternalV1OperationsOidSnapshotMutationError = ErrorType<Error>
    export type PostInternalV1OperationsOidSnapshotMutationVariables = {oid: string;data: PostInternalV1OperationsOidSnapshotBody}

    /**
 * @summary snapshot
 */
export const usePostInternalV1OperationsOidSnapshot = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInternalV1OperationsOidSnapshot>>, TError,PostInternalV1OperationsOidSnapshotMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postInternalV1OperationsOidSnapshot>>,
        TError,
        PostInternalV1OperationsOidSnapshotMutationVariables,
        TContext
      > => {
      return useMutation(getPostInternalV1OperationsOidSnapshotMutationOptions(options), queryClient);
    }
