/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
export type AccessAllowedAction = typeof AccessAllowedAction[keyof typeof AccessAllowedAction];


export const AccessAllowedAction = {
  read: 'read',
  execute: 'execute',
} as const;

export interface Access {
  allowedAction: AccessAllowedAction;
  executable: boolean;
  runtimeGeneration: number;
  tenantId: string;
  userId: string;
  workspaceId: string;
}

export interface AdminOperation {
  createdAt: string;
  id: string;
  kind: string;
  projectId: string;
  state: string;
  step: string;
  tenantId: string;
  updatedAt: string;
  version: number;
  /** @nullable */
  workspaceId: string | null;
}

export type AdminResourceDesiredState = typeof AdminResourceDesiredState[keyof typeof AdminResourceDesiredState];


export const AdminResourceDesiredState = {
  running: 'running',
  stopped: 'stopped',
  deleted: 'deleted',
} as const;

export type AdminResourceKind = typeof AdminResourceKind[keyof typeof AdminResourceKind];


export const AdminResourceKind = {
  main: 'main',
  isolated: 'isolated',
} as const;

export type AdminResourceObservedState = typeof AdminResourceObservedState[keyof typeof AdminResourceObservedState];


export const AdminResourceObservedState = {
  provisioning: 'provisioning',
  starting: 'starting',
  ready: 'ready',
  stopping: 'stopping',
  stopped: 'stopped',
  unavailable: 'unavailable',
  deleting: 'deleting',
  deleted: 'deleted',
} as const;

export interface AdminResource {
  desiredState: AdminResourceDesiredState;
  id: string;
  kind: AdminResourceKind;
  observedState: AdminResourceObservedState;
  ownerUserId: string;
  projectId: string;
  runtimeGeneration: number;
  version: number;
}

/**
 * @nullable
 */
export type AssistSuggestionExplanations = { [key: string]: unknown } | null;

export type AssistSuggestionSuggestedValues = { [key: string]: unknown };

export type ContextRefRefRefType = typeof ContextRefRefRefType[keyof typeof ContextRefRefRefType];


export const ContextRefRefRefType = {
  parent_issue: 'parent_issue',
  run: 'run',
  timeline_message: 'timeline_message',
  pull_request: 'pull_request',
  project: 'project',
  workspace: 'workspace',
  acceptance_criteria: 'acceptance_criteria',
} as const;

export interface ContextRefRef {
  refId: string;
  refType: ContextRefRefRefType;
}

export interface AssistSuggestion {
  /** @nullable */
  explanations?: AssistSuggestionExplanations;
  suggestedContextRefs: ContextRefRef[];
  suggestedValues: AssistSuggestionSuggestedValues;
}

export type CloneExecutionInput = { [key: string]: unknown };

/**
 * @nullable
 */
export type CloneExecutionResult = { [key: string]: unknown } | null;

export interface CloneExecution {
  /** @nullable */
  cloneRequestId: string | null;
  createdAt: string;
  /** @nullable */
  credentialRefId?: string | null;
  /** @nullable */
  credentialRefVersion?: number | null;
  dispatchedEpoch: number;
  executionId: string;
  input: CloneExecutionInput;
  nodeId: string;
  nodeOperationId: string;
  operationId: string;
  /** @nullable */
  result: CloneExecutionResult;
  /** @nullable */
  terminatedByForceStopId: string | null;
  updatedAt: string;
  /** @nullable */
  workspaceId: string | null;
}

export type CloneStateKind = typeof CloneStateKind[keyof typeof CloneStateKind];


export const CloneStateKind = {
  pending: 'pending',
  succeeded: 'succeeded',
  failed: 'failed',
} as const;

export type CloneStateReason = typeof CloneStateReason[keyof typeof CloneStateReason];


export const CloneStateReason = {
  sourceUnavailable: 'sourceUnavailable',
  branchNotFound: 'branchNotFound',
  destinationConflict: 'destinationConflict',
  operationFailed: 'operationFailed',
  interrupted: 'interrupted',
  unspecified: 'unspecified',
} as const;

export interface CloneState {
  commit?: string;
  kind: CloneStateKind;
  path?: string;
  reason?: CloneStateReason;
  retainedPath?: string;
}

export interface CloneOperation {
  branch: string;
  createdAt: string;
  /** @nullable */
  executionId: string | null;
  /** @nullable */
  nodeId: string | null;
  operationId: string;
  repository: string;
  requestId: string;
  state: CloneState;
  updatedAt: string;
}

export type CollaborationTargetType = typeof CollaborationTargetType[keyof typeof CollaborationTargetType];


export const CollaborationTargetType = {
  user: 'user',
  agent: 'agent',
  team: 'team',
  workflow: 'workflow',
} as const;

export type InteractionDescriptorMode = typeof InteractionDescriptorMode[keyof typeof InteractionDescriptorMode];


export const InteractionDescriptorMode = {
  mention: 'mention',
  task: 'task',
  form: 'form',
} as const;

export interface InteractionDescriptor {
  /** @nullable */
  formRef?: string | null;
  mode: InteractionDescriptorMode;
  requiresTask: boolean;
}

export interface CollaborationTarget {
  description: string;
  displayName: string;
  id: string;
  interactionDescriptor: InteractionDescriptor;
  type: CollaborationTargetType;
}

export interface Comment {
  /** @nullable */
  authorId: string | null;
  authorType: string;
  /** @nullable */
  authorUserId: string | null;
  body: string;
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  id: string;
  issueId: string;
  /** @nullable */
  parentId: string | null;
  seq: number;
  tenantId: string;
  updatedAt: string;
  version: number;
}

export type ContextRefRefType = typeof ContextRefRefType[keyof typeof ContextRefRefType];


export const ContextRefRefType = {
  parent_issue: 'parent_issue',
  run: 'run',
  timeline_message: 'timeline_message',
  pull_request: 'pull_request',
  project: 'project',
  workspace: 'workspace',
  acceptance_criteria: 'acceptance_criteria',
} as const;

export interface ContextRef {
  createdAt: string;
  id: string;
  issueId: string;
  refId: string;
  refType: ContextRefRefType;
  tenantId: string;
}

export interface ControllerProject {
  createdAt: string;
  /** @nullable */
  credentialRefId: string | null;
  defaultBranch: string;
  /** @nullable */
  deletedAt: string | null;
  id: string;
  lifecycle: string;
  name: string;
  ownerUserId: string;
  /** @nullable */
  repositoryCredentialRefId?: string | null;
  repositoryUrl: string;
  /** @nullable */
  secretRef: string | null;
  spaceId: string;
  tenantId: string;
  version: number;
}

export interface ControllerWorkspace {
  admissionEpoch: number;
  admissionOpen: boolean;
  /**
     * @nullable
     * @pattern ^([0-9a-f]{40}|[0-9a-f]{64})$
     */
  baseCommitId: string | null;
  createdAt: string;
  creatorEvidence: string;
  /** @nullable */
  creatorOperationId: string | null;
  /** @nullable */
  creatorUserId: string | null;
  /** @nullable */
  deletedAt: string | null;
  desiredState: string;
  id: string;
  /** @nullable */
  issueRunId?: string | null;
  kind: string;
  observedState: string;
  ownerUserId: string;
  projectId: string;
  requestedRef: string;
  runtimeGeneration: number;
  tenantId: string;
  version: number;
}

export interface DirectoryPerson {
  departmentName: string;
  employeeNumber: string;
  globalUserId: string;
  name: string;
}

export type EffectRequestKind = typeof EffectRequestKind[keyof typeof EffectRequestKind];


export const EffectRequestKind = {
  storage_ensure: 'storage_ensure',
  worktree_ensure: 'worktree_ensure',
  sandbox_ensure: 'sandbox_ensure',
  sandbox_terminate: 'sandbox_terminate',
  worktree_delete: 'worktree_delete',
  storage_delete: 'storage_delete',
  workspace_data_delete: 'workspace_data_delete',
  plugin_ensure: 'plugin_ensure',
  plugin_delete: 'plugin_delete',
} as const;

export interface PluginReleaseTarget {
  sha256: string;
  target: string;
  url: string;
}

export interface PluginUniversalRelease {
  sha256: string;
  url: string;
}

export interface EffectRequest {
  kind: EffectRequestKind;
  pluginId?: string;
  projectId: string;
  repositoryUrl?: string;
  requestedRef?: string;
  sandboxInstanceId?: string;
  targets?: PluginReleaseTarget[];
  universal?: PluginUniversalRelease;
  version?: string;
  workspaceId?: string;
}

export interface EffectResult {
  /** @pattern ^([0-9a-f]{40}|[0-9a-f]{64})$ */
  commitId?: string;
  diagnostic?: string;
  error?: string;
  installed?: boolean;
  jobTerminated?: boolean;
  lateEnsureFenced?: boolean;
  layoutVersion?: number;
  nodeId?: string;
  removed?: boolean;
  sandboxInstanceId?: string;
  terminated?: boolean;
  version?: string;
}

export interface Effect {
  createdAt: string;
  /** @nullable */
  externalId: string | null;
  id: string;
  kind: string;
  operationId: string;
  projectId: string;
  reconciledEpoch: number;
  request: EffectRequest;
  result: EffectResult;
  state: string;
  version: number;
  /** @nullable */
  workspaceId: string | null;
}

/**
 * @nullable
 */
export type EmptyClaimOperation = typeof EmptyClaimOperation[keyof typeof EmptyClaimOperation] | null;


export const EmptyClaimOperation = {
} as const;

export interface EmptyClaim {
  /** @nullable */
  operation: EmptyClaimOperation;
}

export type ErrorParams = { [key: string]: unknown };

export interface Error {
  code: string;
  params: ErrorParams;
  requestId: string;
}

export interface FormOption {
  label: string;
  value: string;
}

export type FormFieldType = typeof FormFieldType[keyof typeof FormFieldType];


export const FormFieldType = {
  text: 'text',
  textarea: 'textarea',
  number: 'number',
  boolean: 'boolean',
  select: 'select',
  multi_select: 'multi_select',
} as const;

export interface FormField {
  /** Type-consistent with `type`; an array of strings for multi_select. */
  defaultValue?: unknown | null;
  /** @nullable */
  description?: string | null;
  key: string;
  label: string;
  /** @nullable */
  options?: FormOption[] | null;
  /** @nullable */
  placeholder?: string | null;
  required: boolean;
  type: FormFieldType;
}

export interface FormDescriptor {
  /** @nullable */
  description?: string | null;
  fields: FormField[];
  formRef: string;
  /** @nullable */
  title?: string | null;
}

export interface GitIdentity {
  email: string;
  isDefault: boolean;
  name: string;
  version: number;
}

export interface HuaweiMember {
  displayName: string;
  role: string;
  status: string;
  tenantId: string;
  userId: string;
  version: number;
}

export type IdleRefusalErrorCode = typeof IdleRefusalErrorCode[keyof typeof IdleRefusalErrorCode];


export const IdleRefusalErrorCode = {
  resource_in_use: 'resource_in_use',
} as const;

export interface IdleRefusal {
  accepted: boolean;
  errorCode: IdleRefusalErrorCode;
}

export interface Invitation {
  /** @nullable */
  consumedAt?: string | null;
  /** @nullable */
  consumedBy?: string | null;
  createdAt: string;
  createdBy: string;
  expiresAt: string;
  id: string;
  /** @nullable */
  revokedAt?: string | null;
  tenantId: string;
  version: number;
}

export type IssueAssigneeType = typeof IssueAssigneeType[keyof typeof IssueAssigneeType];


export const IssueAssigneeType = {
  user: 'user',
  agent: 'agent',
  team: 'team',
} as const;

export type IssuePriority = typeof IssuePriority[keyof typeof IssuePriority];


export const IssuePriority = {
  urgent: 'urgent',
  high: 'high',
  medium: 'medium',
  low: 'low',
  none: 'none',
} as const;

export type IssueProperties = { [key: string]: unknown };

export interface Label {
  color: string;
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  id: string;
  name: string;
  tenantId: string;
  updatedAt: string;
  version: number;
}

export interface Issue {
  /** @nullable */
  assigneeId: string | null;
  assigneeType: IssueAssigneeType;
  /** @nullable */
  assigneeUserId: string | null;
  createdAt: string;
  creatorUserId: string;
  /** @nullable */
  deletedAt: string | null;
  description: string;
  id: string;
  labels: Label[];
  number: number;
  /** @nullable */
  parentIssueId: string | null;
  position: number;
  priority: IssuePriority;
  /** @nullable */
  projectRef: string | null;
  properties: IssueProperties;
  /** @pattern ^[a-z0-9][a-z0-9_]{0,31}$ */
  status: string;
  tenantId: string;
  title: string;
  updatedAt: string;
  version: number;
}

export type IssueInteractionInput = { [key: string]: unknown };

export type IssueInteractionMode = typeof IssueInteractionMode[keyof typeof IssueInteractionMode];


export const IssueInteractionMode = {
  mention: 'mention',
  task: 'task',
  form: 'form',
} as const;

export type IssueInteractionTargetType = typeof IssueInteractionTargetType[keyof typeof IssueInteractionTargetType];


export const IssueInteractionTargetType = {
  user: 'user',
  agent: 'agent',
  team: 'team',
  workflow: 'workflow',
} as const;

export interface IssueInteraction {
  commentId: string;
  createdAt: string;
  id: string;
  input: IssueInteractionInput;
  issueId: string;
  mode: IssueInteractionMode;
  /** @nullable */
  runId: string | null;
  targetId: string;
  targetType: IssueInteractionTargetType;
  task: string;
  tenantId: string;
}

export type IssueRunExecutorType = typeof IssueRunExecutorType[keyof typeof IssueRunExecutorType];


export const IssueRunExecutorType = {
  agent: 'agent',
  team: 'team',
  workflow: 'workflow',
} as const;

export type IssueRunInput = { [key: string]: unknown };

export type IssueRunPreparationStage = typeof IssueRunPreparationStage[keyof typeof IssueRunPreparationStage];


export const IssueRunPreparationStage = {
  waiting: 'waiting',
  environment: 'environment',
  clone: 'clone',
  plugin: 'plugin',
  start: 'start',
  failed: 'failed',
  cancelled: 'cancelled',
} as const;

/**
 * @nullable
 */
export type IssueRunPreparation = {
  cloneAttempts: number;
  /** @nullable */
  errorCode: string | null;
  maxCloneAttempts: number;
  /** @nullable */
  retryAt: string | null;
  stage: IssueRunPreparationStage;
} | null;

/**
 * @nullable
 */
export type IssueRunResult = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type IssueRunRevision = {
  baseCommit: string;
  /** @nullable */
  bundleSize: number | null;
  changed: boolean;
  createdAt: string;
  finalCommit: string;
  historySize: number;
  id: string;
  /** @nullable */
  priorRevisionId: string | null;
} | null;

export type IssueRunStatus = typeof IssueRunStatus[keyof typeof IssueRunStatus];


export const IssueRunStatus = {
  queued: 'queued',
  dispatched: 'dispatched',
  running: 'running',
  completed: 'completed',
  failed: 'failed',
  cancelled: 'cancelled',
  deferred: 'deferred',
} as const;

export interface IssueRun {
  attempt: number;
  /** @nullable */
  completedAt: string | null;
  createdAt: string;
  /** @nullable */
  delegatedFromRunId: string | null;
  /** @nullable */
  deletedAt: string | null;
  /** @nullable */
  dispatchedAt: string | null;
  error: string;
  /** @nullable */
  executionContextRef: string | null;
  executorId: string;
  executorType: IssueRunExecutorType;
  externalExecutionId: string;
  failureReason: string;
  /** @nullable */
  fireAt: string | null;
  id: string;
  input: IssueRunInput;
  issueId: string;
  /** @nullable */
  leaseExpiresAt: string | null;
  maxAttempts: number;
  /** @nullable */
  parentRunId: string | null;
  /** @nullable */
  preparation?: IssueRunPreparation;
  queuedAt: string;
  /** @nullable */
  rerunOfRunId: string | null;
  /** @nullable */
  result: IssueRunResult;
  /** @nullable */
  resumeRevisionId: string | null;
  /** @nullable */
  retryOfRunId: string | null;
  /** @nullable */
  revision?: IssueRunRevision;
  /** @nullable */
  startedAt: string | null;
  status: IssueRunStatus;
  tenantId: string;
  triggerEvidenceKind: string;
  /** @nullable */
  triggerEvidenceRefId: string | null;
  triggerSummary: string;
  updatedAt: string;
  version: number;
  /** @nullable */
  workflowInvocationRef: string | null;
}

export type IssueStatusCategory = typeof IssueStatusCategory[keyof typeof IssueStatusCategory];


export const IssueStatusCategory = {
  unstarted: 'unstarted',
  started: 'started',
  done: 'done',
  closed: 'closed',
} as const;

export interface IssueStatus {
  category: IssueStatusCategory;
  color: string;
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  description: string;
  icon: string;
  id: string;
  isSystem: boolean;
  key: string;
  name: string;
  position: number;
  tenantId: string;
  updatedAt: string;
  version: number;
}

export type IssueViewFilter = { [key: string]: unknown };

export interface IssueView {
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  filter: IssueViewFilter;
  id: string;
  name: string;
  ownerUserId: string;
  tenantId: string;
  updatedAt: string;
  version: number;
}

export interface JoinLink {
  createdAt: string;
  createdBy: string;
  expiresAt: string;
  id: string;
  /** @nullable */
  revokedAt?: string | null;
  tenantId: string;
  version: number;
}

export type JoinRequestStatus = typeof JoinRequestStatus[keyof typeof JoinRequestStatus];


export const JoinRequestStatus = {
  pending: 'pending',
  approved: 'approved',
  rejected: 'rejected',
} as const;

export interface JoinRequest {
  createdAt: string;
  /** @nullable */
  decidedAt?: string | null;
  /** @nullable */
  decidedBy?: string | null;
  displayName?: string;
  id: string;
  linkId: string;
  name?: string;
  status: JoinRequestStatus;
  tenantId: string;
  userId: string;
  version: number;
}

export interface JoinedMembership {
  name: string;
  role: string;
  status: string;
  tenantId: string;
  userId: string;
  version: number;
}

export interface Lease {
  epoch: number;
  expiresAt: string;
  holderId: string;
  name: string;
}

export interface Member {
  createdAt: string;
  role: string;
  status: string;
  tenantId: string;
  userId: string;
  version: number;
}

export interface MemberListItem {
  displayName: string;
  id: string;
  role: string;
  status: string;
  tenantId: string;
  userId: string;
  version: number;
}

export type ModelConnectionAuthMode = typeof ModelConnectionAuthMode[keyof typeof ModelConnectionAuthMode];


export const ModelConnectionAuthMode = {
  bearer: 'bearer',
  'x-api-key': 'x-api-key',
} as const;

export type ModelConnectionProtocol = typeof ModelConnectionProtocol[keyof typeof ModelConnectionProtocol];


export const ModelConnectionProtocol = {
  'openai-completions': 'openai-completions',
  'anthropic-messages': 'anthropic-messages',
} as const;

export interface ModelDefinition {
  contextWindow: number;
  id: string;
  maxTokens: number;
  name: string;
}

export interface ModelConnection {
  authMode: ModelConnectionAuthMode;
  baseUrl: string;
  createdAt: string;
  credentialConfigured: boolean;
  enabled: boolean;
  id: string;
  models: ModelDefinition[];
  name: string;
  protocol: ModelConnectionProtocol;
  updatedAt: string;
  version: number;
}

export interface ModelDefault {
  connectionId: string;
  modelId: string;
  version: number;
}

export interface Node {
  connectionState: string;
  /** @nullable */
  endedAt: string | null;
  id: string;
  /** @nullable */
  idleAdmissionEpoch: number | null;
  initialized: boolean;
  lastSeenAt: string;
  /** @nullable */
  nodeId: string | null;
  /** @nullable */
  nodeIncarnationId: string | null;
  protocolVersion: number;
  sandboxInstanceId: string;
  serviceSubject: string;
  version: number;
  workspaceId: string;
}

export type NodeExecutionInput = { [key: string]: unknown };

/**
 * @nullable
 */
export type NodeExecutionResult = { [key: string]: unknown } | null;

export interface NodeExecution {
  createdAt: string;
  dispatchedEpoch: number;
  executionId: string;
  input: NodeExecutionInput;
  kind: string;
  lastEventSequence: number;
  nodeId: string;
  nodeOperationId: string;
  operationId: string;
  /** @nullable */
  result: NodeExecutionResult;
  /** @nullable */
  terminatedByForceStopId: string | null;
  updatedAt: string;
  /** @nullable */
  workId: string | null;
  /** @nullable */
  workspaceId: string | null;
}

export type OperationState = typeof OperationState[keyof typeof OperationState];


export const OperationState = {
  queued: 'queued',
  running: 'running',
  retry_wait: 'retry_wait',
  blocked: 'blocked',
  succeeded: 'succeeded',
  failed: 'failed',
} as const;

export type OperationStep = typeof OperationStep[keyof typeof OperationStep];


export const OperationStep = {
  storage: 'storage',
  worktree: 'worktree',
  sandbox: 'sandbox',
  node: 'node',
  clone: 'clone',
  ready: 'ready',
  quiesce: 'quiesce',
  terminate: 'terminate',
  cleanup: 'cleanup',
  storage_delete: 'storage_delete',
  plugin: 'plugin',
  done: 'done',
} as const;

export type WorkspaceDesiredState = typeof WorkspaceDesiredState[keyof typeof WorkspaceDesiredState];


export const WorkspaceDesiredState = {
  running: 'running',
  stopped: 'stopped',
  deleted: 'deleted',
} as const;

export type WorkspaceKind = typeof WorkspaceKind[keyof typeof WorkspaceKind];


export const WorkspaceKind = {
  main: 'main',
  isolated: 'isolated',
} as const;

export type WorkspaceObservedState = typeof WorkspaceObservedState[keyof typeof WorkspaceObservedState];


export const WorkspaceObservedState = {
  provisioning: 'provisioning',
  starting: 'starting',
  ready: 'ready',
  stopping: 'stopping',
  stopped: 'stopped',
  unavailable: 'unavailable',
  deleting: 'deleting',
  deleted: 'deleted',
} as const;

export interface Workspace {
  admissionEpoch: number;
  admissionOpen: boolean;
  /**
     * @nullable
     * @pattern ^([0-9a-f]{40}|[0-9a-f]{64})$
     */
  baseCommitId: string | null;
  createdAt: string;
  creatorEvidence: string;
  /** @nullable */
  creatorOperationId: string | null;
  /** @nullable */
  creatorUserId: string | null;
  /** @nullable */
  deletedAt: string | null;
  desiredState: WorkspaceDesiredState;
  id: string;
  kind: WorkspaceKind;
  observedState: WorkspaceObservedState;
  ownerUserId: string;
  projectId: string;
  requestedRef: string;
  runtimeGeneration: number;
  tenantId: string;
  version: number;
}

export type PluginCatalogEntryKind = typeof PluginCatalogEntryKind[keyof typeof PluginCatalogEntryKind];


export const PluginCatalogEntryKind = {
  workbench: 'workbench',
  agent: 'agent',
  webview: 'webview',
  skill: 'skill',
  mcp: 'mcp',
  hook: 'hook',
  pack: 'pack',
  workflow: 'workflow',
} as const;

export type PluginLogoCandidateExtension = typeof PluginLogoCandidateExtension[keyof typeof PluginLogoCandidateExtension];


export const PluginLogoCandidateExtension = {
  svg: 'svg',
  png: 'png',
  webp: 'webp',
  jpg: 'jpg',
  jpeg: 'jpeg',
} as const;

export type PluginLogoCandidateRole = typeof PluginLogoCandidateRole[keyof typeof PluginLogoCandidateRole];


export const PluginLogoCandidateRole = {
  universal: 'universal',
  light: 'light',
  dark: 'dark',
} as const;

export interface PluginLogoCandidate {
  extension: PluginLogoCandidateExtension;
  role: PluginLogoCandidateRole;
}

export type PluginCatalogEntryLogo = {
  universal: PluginLogoCandidate;
} | {
  dark: PluginLogoCandidate;
  light: PluginLogoCandidate;
} | null;

export interface PluginCatalogEntry {
  description: string;
  /** @nullable */
  homepage: string | null;
  id: string;
  identifier: string;
  indexedAt: string;
  kind: PluginCatalogEntryKind;
  /** @nullable */
  license: string | null;
  logo: PluginCatalogEntryLogo;
  marketplaceVisible: boolean;
  /** @nullable */
  packMembers: string[] | null;
  /** @nullable */
  readme: string | null;
  /** @nullable */
  sha256: string | null;
  sourceNamespace: string;
  sourceUrl: string;
  /** @nullable */
  targets: PluginReleaseTarget[] | null;
  title: string;
  /** @nullable */
  url: string | null;
  version: string;
}

export type OperationRequestPluginMetaItem = {
  desiredRevision: number;
  pluginId: string;
};

export type OperationRequestPluginsItem = { [key: string]: unknown };

export type OperationRequestPrevious = {[key: string]: Workspace};

export interface OperationRequest {
  desiredRevision?: number;
  pluginId?: string;
  pluginMeta?: OperationRequestPluginMetaItem[];
  plugins?: OperationRequestPluginsItem[];
  previous?: OperationRequestPrevious;
  release?: PluginCatalogEntry;
  version?: string;
}

export interface OperationResult {
  forceStopId?: string;
  resourceId?: string;
}

export interface Operation {
  actorUserId: string;
  /** @nullable */
  controllerEpoch: number | null;
  createdAt: string;
  /** @nullable */
  errorCode: string | null;
  id: string;
  idempotencyKey: string;
  kind: string;
  projectId: string;
  request: OperationRequest;
  requestHash: string;
  result: OperationResult;
  /** @nullable */
  retryAt: string | null;
  state: OperationState;
  step: OperationStep;
  tenantId: string;
  updatedAt: string;
  version: number;
  /** @nullable */
  workspaceId: string | null;
}

export interface PluginCatalog {
  items: PluginCatalogEntry[];
  /** @nullable */
  syncedAt?: string | null;
}

export interface Project {
  createdAt: string;
  /** @nullable */
  credentialRefId: string | null;
  defaultBranch: string;
  /** @nullable */
  deletedAt: string | null;
  id: string;
  lifecycle: string;
  name: string;
  ownerUserId: string;
  /** @nullable */
  repositoryCredentialRefId?: string | null;
  repositoryUrl: string;
  spaceId: string;
  tenantId: string;
  version: number;
}

export type RunPreparationStage = typeof RunPreparationStage[keyof typeof RunPreparationStage];


export const RunPreparationStage = {
  waiting: 'waiting',
  environment: 'environment',
  clone: 'clone',
  plugin: 'plugin',
  start: 'start',
  failed: 'failed',
  cancelled: 'cancelled',
} as const;

export interface RunPreparation {
  cloneAttempts: number;
  /** @nullable */
  errorCode: string | null;
  maxCloneAttempts: number;
  /** @nullable */
  retryAt: string | null;
  stage: RunPreparationStage;
}

export type RuntimeControlState = typeof RuntimeControlState[keyof typeof RuntimeControlState];


export const RuntimeControlState = {
  idle: 'idle',
  acquiring: 'acquiring',
  held: 'held',
  draining: 'draining',
  reconciling: 'reconciling',
  maintenance: 'maintenance',
} as const;

export interface RuntimeControl {
  controlEpoch: number;
  /** @nullable */
  expiresAt: string | null;
  /** @nullable */
  holderUserId: string | null;
  /** @nullable */
  sessionId?: string | null;
  state: RuntimeControlState;
  version: number;
  workspaceId: string;
}

export type RuntimeForceStopState = typeof RuntimeForceStopState[keyof typeof RuntimeForceStopState];


export const RuntimeForceStopState = {
  registered: 'registered',
  terminating: 'terminating',
  succeeded: 'succeeded',
} as const;

export interface RuntimeForceStop {
  actorUserId: string;
  /** @nullable */
  confirmedAt?: string | null;
  controlEpoch: number;
  /** @nullable */
  controllerEpoch?: number | null;
  createdAt: string;
  id: string;
  reason: string;
  runtimeGeneration: number;
  state: RuntimeForceStopState;
  tenantId: string;
  version: number;
  workspaceId: string;
}

export interface Sandbox {
  createdAt: string;
  generation: number;
  id: string;
  observedState: string;
  /** @nullable */
  substrateSandboxId: string | null;
  /** @nullable */
  terminatedAt: string | null;
  version: number;
  workspaceId: string;
}

export type SnapshotPluginInput = { [key: string]: unknown };

export interface Snapshot {
  clones: CloneExecution[];
  effects: Effect[];
  nodes: Node[];
  operation: Operation;
  pluginExecutions: NodeExecution[];
  pluginInput?: SnapshotPluginInput;
  project: ControllerProject;
  sandboxes: Sandbox[];
  workspaces: ControllerWorkspace[];
}

export interface Space {
  /** @nullable */
  archivedAt: string | null;
  createdAt: string;
  createdBy: string;
  description: string;
  id: string;
  name: string;
  slug: string;
  tenantId: string;
  updatedAt: string;
  version: number;
}

export type SpaceEventType = typeof SpaceEventType[keyof typeof SpaceEventType];


export const SpaceEventType = {
  spaceupdated: 'space.updated',
  spacemember_updated: 'space.member_updated',
  projectcreated: 'project.created',
  projectupdated: 'project.updated',
  projectarchived: 'project.archived',
  spaceplugins_updated: 'space.plugins_updated',
  pluginscatalog_updated: 'plugins.catalog_updated',
  issue_runthread_appended: 'issue_run.thread_appended',
  issue_runthread_changed: 'issue_run.thread_changed',
} as const;

export interface SpaceEvent {
  issueId?: string;
  lastSeq?: number;
  /** @nullable */
  projectId?: string | null;
  runId?: string;
  spaceId: string;
  type: SpaceEventType;
  version?: number;
}

export interface SpaceListItem {
  /** @nullable */
  archivedAt: string | null;
  createdAt: string;
  createdBy: string;
  description: string;
  id: string;
  name: string;
  role: string;
  slug: string;
  tenantId: string;
  updatedAt: string;
  version: number;
}

export type SpacePluginDesiredState = typeof SpacePluginDesiredState[keyof typeof SpacePluginDesiredState];


export const SpacePluginDesiredState = {
  installed: 'installed',
  removed: 'removed',
} as const;

export type SpacePluginObservedState = typeof SpacePluginObservedState[keyof typeof SpacePluginObservedState];


export const SpacePluginObservedState = {
  pending: 'pending',
  installing: 'installing',
  installed: 'installed',
  failed: 'failed',
  removing: 'removing',
  removed: 'removed',
} as const;

export interface SpacePlugin {
  affectedCount?: number;
  completedCount?: number;
  createdAt: string;
  desiredRevision?: number;
  desiredState: SpacePluginDesiredState;
  desiredVersion: string;
  failedCount?: number;
  id: string;
  identifier: string;
  /** @nullable */
  installError: string | null;
  observedState: SpacePluginObservedState;
  /** @nullable */
  observedVersion: string | null;
  /** @nullable */
  requestedByUserId?: string | null;
  sourceNamespace: string;
  spaceId: string;
  tenantId: string;
  unavailableCount?: number;
  updatedAt: string;
  version: number;
  waitingControlCount?: number;
  waitingStartCount?: number;
}

export interface SpacePluginList {
  items: SpacePlugin[];
}

export interface Tenant {
  id: string;
  name: string;
  role: string;
  status: string;
}

export interface TenantCreated {
  space: Space;
  tenant: Tenant;
}

export type ThreadEntryRecord = { [key: string]: unknown };

export type ThreadEntrySource = typeof ThreadEntrySource[keyof typeof ThreadEntrySource];


export const ThreadEntrySource = {
  node: 'node',
  user: 'user',
  system: 'system',
} as const;

/**
 * User-turn lifecycle. Null for node and system entries.
 * @nullable
 */
export type ThreadEntryStatus = typeof ThreadEntryStatus[keyof typeof ThreadEntryStatus] | null;


export const ThreadEntryStatus = {
  queued: 'queued',
  delivered: 'delivered',
  discarded: 'discarded',
} as const;

export interface ThreadEntry {
  createdAt: string;
  kind: string;
  record: ThreadEntryRecord;
  /** @minimum 1 */
  seq: number;
  source: ThreadEntrySource;
  /**
     * User-turn lifecycle. Null for node and system entries.
     * @nullable
     */
  status?: ThreadEntryStatus;
  /** @nullable */
  turnId?: string | null;
}

export interface ThreadModel {
  connectionName: string;
  modelId: string;
  modelName: string;
}

export interface Ticket {
  actorUserId: string;
  admissionEpoch: number;
  /** @nullable */
  controlEpoch: number | null;
  /** @nullable */
  controlSessionId: string | null;
  createdAt: string;
  /** @nullable */
  finishedAt: string | null;
  id: string;
  kind: string;
  nodeInstanceId: string;
  state: string;
  tenantId: string;
  /** @nullable */
  terminatedByForceStopId: string | null;
  version: number;
  workspaceId: string;
}

export type TimelineEntryAuthorType = typeof TimelineEntryAuthorType[keyof typeof TimelineEntryAuthorType];


export const TimelineEntryAuthorType = {
  user: 'user',
  agent: 'agent',
  team: 'team',
  system: 'system',
} as const;

/**
 * @nullable
 */
export type TimelineEntryDetails = { [key: string]: unknown } | null;

export type TimelineEntryKind = typeof TimelineEntryKind[keyof typeof TimelineEntryKind];


export const TimelineEntryKind = {
  comment: 'comment',
  activity: 'activity',
} as const;

export interface TimelineEntry {
  /** @nullable */
  action: string | null;
  /** @nullable */
  authorId: string | null;
  authorType: TimelineEntryAuthorType;
  /** @nullable */
  authorUserId: string | null;
  /** @nullable */
  body: string | null;
  createdAt: string;
  /** @nullable */
  details: TimelineEntryDetails;
  id: string;
  kind: TimelineEntryKind;
  /** @nullable */
  parentId: string | null;
  seq: number;
}

export interface User {
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  displayName: string;
  id: string;
  status: string;
  version: number;
}

/**
 * The authored graph document: nodes, edges, viewport, editor annotations and global variables. Stored and returned whole; the editor is its only reader.
 */
export type WorkflowGraph = { [key: string]: unknown };

export interface Workflow {
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  description: string;
  /** The authored graph document: nodes, edges, viewport, editor annotations and global variables. Stored and returned whole; the editor is its only reader. */
  graph: WorkflowGraph;
  id: string;
  name: string;
  tenantId: string;
  updatedAt: string;
  version: number;
}

/**
 * The frozen graph document this run executed against, from the snapshot it captured.
 * @nullable
 */
export type WorkflowRunDefinitionSnapshot = { [key: string]: unknown } | null;

/**
 * The kickoff input passed to the run's start node.
 */
export type WorkflowRunInput = { [key: string]: unknown };

/**
 * Per-node execution state keyed by node id: status, output, error, timestamps.
 */
export type WorkflowRunNodeStates = { [key: string]: unknown };

export type WorkflowRunRoundsItem = { [key: string]: unknown };

export type WorkflowRunStatus = typeof WorkflowRunStatus[keyof typeof WorkflowRunStatus];


export const WorkflowRunStatus = {
  pending: 'pending',
  running: 'running',
  awaiting_input: 'awaiting_input',
  succeeded: 'succeeded',
  failed: 'failed',
  cancelled: 'cancelled',
} as const;

export interface WorkflowRun {
  createdAt: string;
  /**
     * The frozen graph document this run executed against, from the snapshot it captured.
     * @nullable
     */
  definitionSnapshot?: WorkflowRunDefinitionSnapshot;
  error: string;
  /** @nullable */
  finishedAt: string | null;
  id: string;
  /** The kickoff input passed to the run's start node. */
  input: WorkflowRunInput;
  name: string;
  /** Per-node execution state keyed by node id: status, output, error, timestamps. */
  nodeStates: WorkflowRunNodeStates;
  rounds: WorkflowRunRoundsItem[];
  snapshotId: string;
  /** @nullable */
  startedAt: string | null;
  status: WorkflowRunStatus;
  tenantId: string;
  updatedAt: string;
  workflowId: string;
  workflowName: string;
}

/**
 * The graph document frozen at publish time; restoring this snapshot writes it back to the workflow's live graph.
 */
export type WorkflowSnapshotGraph = { [key: string]: unknown };

export interface WorkflowSnapshot {
  createdAt: string;
  /** The graph document frozen at publish time; restoring this snapshot writes it back to the workflow's live graph. */
  graph: WorkflowSnapshotGraph;
  id: string;
  name: string;
  tenantId: string;
  version: number;
  workflowId: string;
}

export type WorkspaceListItemDesiredState = typeof WorkspaceListItemDesiredState[keyof typeof WorkspaceListItemDesiredState];


export const WorkspaceListItemDesiredState = {
  running: 'running',
  stopped: 'stopped',
  deleted: 'deleted',
} as const;

export type WorkspaceListItemKind = typeof WorkspaceListItemKind[keyof typeof WorkspaceListItemKind];


export const WorkspaceListItemKind = {
  main: 'main',
  isolated: 'isolated',
} as const;

export type WorkspaceListItemObservedState = typeof WorkspaceListItemObservedState[keyof typeof WorkspaceListItemObservedState];


export const WorkspaceListItemObservedState = {
  provisioning: 'provisioning',
  starting: 'starting',
  ready: 'ready',
  stopping: 'stopping',
  stopped: 'stopped',
  unavailable: 'unavailable',
  deleting: 'deleting',
  deleted: 'deleted',
} as const;

export interface WorkspaceListItem {
  admissionEpoch?: number;
  admissionOpen?: boolean;
  /**
     * @nullable
     * @pattern ^([0-9a-f]{40}|[0-9a-f]{64})$
     */
  baseCommitId?: string | null;
  /** @nullable */
  branchName?: string | null;
  canUse: boolean;
  createdAt: string;
  creatorEvidence: string;
  /** @nullable */
  creatorOperationId?: string | null;
  /** @nullable */
  creatorUserId: string | null;
  /** @nullable */
  deletedAt: string | null;
  desiredState: WorkspaceListItemDesiredState;
  id: string;
  kind: WorkspaceListItemKind;
  observedState: WorkspaceListItemObservedState;
  ownerUserId: string;
  projectId: string;
  requestedRef?: string;
  runtimeGeneration: number;
  tenantId: string;
  /** @nullable */
  title?: string | null;
  version: number;
}

export type PostApiV1JoinInvitationsRedeemBody = {
  token: string;
};

export type PostApiV1JoinRequestsBody = {
  token: string;
};

export type DeleteApiV1MeGitIdentityBody = {
  /** @minimum 0 */
  version: number;
};

export type PutApiV1MeGitIdentityBody = {
  email: string;
  name: string;
  /** @minimum 0 */
  version?: number;
};

export type GetApiV1MeJoinRequestsParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1MeJoinRequests200 = {
  items: JoinRequest[];
  nextCursor: string;
};

export type GetApiV1MeModelConnectionsParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1MeModelConnections200 = {
  items: ModelConnection[];
  nextCursor: string;
};

export type PostApiV1MeModelConnectionsBodyAuthMode = typeof PostApiV1MeModelConnectionsBodyAuthMode[keyof typeof PostApiV1MeModelConnectionsBodyAuthMode];


export const PostApiV1MeModelConnectionsBodyAuthMode = {
  bearer: 'bearer',
  'x-api-key': 'x-api-key',
} as const;

export type PostApiV1MeModelConnectionsBodyProtocol = typeof PostApiV1MeModelConnectionsBodyProtocol[keyof typeof PostApiV1MeModelConnectionsBodyProtocol];


export const PostApiV1MeModelConnectionsBodyProtocol = {
  'openai-completions': 'openai-completions',
  'anthropic-messages': 'anthropic-messages',
} as const;

export type PostApiV1MeModelConnectionsBody = {
  authMode: PostApiV1MeModelConnectionsBodyAuthMode;
  /**
     * Public HTTPS model API base URL; requests are restricted to the selected protocol endpoints.
     * @maxLength 2048
     */
  baseUrl: string;
  enabled?: boolean;
  models: ModelDefinition[];
  name: string;
  protocol: PostApiV1MeModelConnectionsBodyProtocol;
};

export type PostApiV1MeModelConnections201 = {
  resource: ModelConnection;
};

export type DeleteApiV1MeModelConnectionsMcidBody = {
  /** @minimum 0 */
  version: number;
};

export type DeleteApiV1MeModelConnectionsMcid200 = {
  resource: ModelConnection;
};

export type PutApiV1MeModelConnectionsMcidBodyAuthMode = typeof PutApiV1MeModelConnectionsMcidBodyAuthMode[keyof typeof PutApiV1MeModelConnectionsMcidBodyAuthMode];


export const PutApiV1MeModelConnectionsMcidBodyAuthMode = {
  bearer: 'bearer',
  'x-api-key': 'x-api-key',
} as const;

export type PutApiV1MeModelConnectionsMcidBodyProtocol = typeof PutApiV1MeModelConnectionsMcidBodyProtocol[keyof typeof PutApiV1MeModelConnectionsMcidBodyProtocol];


export const PutApiV1MeModelConnectionsMcidBodyProtocol = {
  'openai-completions': 'openai-completions',
  'anthropic-messages': 'anthropic-messages',
} as const;

export type PutApiV1MeModelConnectionsMcidBody = {
  authMode: PutApiV1MeModelConnectionsMcidBodyAuthMode;
  /**
     * Public HTTPS model API base URL; requests are restricted to the selected protocol endpoints.
     * @maxLength 2048
     */
  baseUrl: string;
  enabled?: boolean;
  models: ModelDefinition[];
  name: string;
  protocol: PutApiV1MeModelConnectionsMcidBodyProtocol;
  /** @minimum 0 */
  version: number;
};

export type PutApiV1MeModelConnectionsMcid200 = {
  resource: ModelConnection;
};

export type DeleteApiV1MeModelConnectionsMcidCredentialBody = {
  /** @minimum 0 */
  version: number;
};

export type DeleteApiV1MeModelConnectionsMcidCredential200 = {
  resource: ModelConnection;
};

export type PutApiV1MeModelConnectionsMcidCredentialBody = {
  /**
     * Handled exclusively by model-gateway; never returned or sent to Cloud HTTP.
     * @minLength 1
     * @maxLength 8192
     */
  apiKey: string;
  /** @minimum 0 */
  version: number;
};

export type PutApiV1MeModelConnectionsMcidCredential200 = {
  resource: ModelConnection;
};

export type PutApiV1MeModelDefaultBody = {
  connectionId: string;
  /**
     * @minLength 1
     * @maxLength 500
     */
  modelId: string;
  /** @minimum 0 */
  version: number;
};

export type GetApiV1MeSpacesParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1MeSpaces200 = {
  items: SpaceListItem[];
  nextCursor: string;
};

export type GetApiV1MeTenantsParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1MeTenants200 = {
  items: Tenant[];
  nextCursor: string;
};

export type PostApiV1TenantsBody = {
  name: string;
  /**
     * Lowercase, immutable, globally unique.
     * @pattern ^[a-z0-9][a-z0-9-]{0,63}$
     */
  slug: string;
};

export type GetApiV1TenantsTidClonesParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidClones200 = {
  items: CloneOperation[];
  nextCursor: string;
};

export type PostApiV1TenantsTidClonesBody = {
  branch: string;
  repository: string;
  requestId: string;
};

export type GetApiV1TenantsTidCollaborationFormsFormRefParams = {
/**
 * Issue the form is being configured for. Tailors the descriptor with the platform fields (repository, prompt) and prefills them from the issue's project repository and the workflow's Start prompt. An unknown or foreign issue is 404.
 */
issueId?: string;
};

export type GetApiV1TenantsTidCollaborationTargets200 = {
  items: CollaborationTarget[];
  nextCursor: string;
};

export type GetApiV1TenantsTidInvitationsParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidInvitations200 = {
  items: Invitation[];
  nextCursor: string;
};

export type PostApiV1TenantsTidInvitationsBody = {
  token: string;
};

export type DeleteApiV1TenantsTidInvitationsIidBody = {
  /** @minimum 0 */
  version: number;
};

export type GetApiV1TenantsTidIssueGroups200GroupsItem = {
  items: Issue[];
  key: string;
};

export type GetApiV1TenantsTidIssueGroups200 = {
  groups: GetApiV1TenantsTidIssueGroups200GroupsItem[];
};

export type GetApiV1TenantsTidIssueStatusesParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidIssueStatuses200 = {
  items: IssueStatus[];
  nextCursor: string;
};

export type PostApiV1TenantsTidIssueStatusesBodyCategory = typeof PostApiV1TenantsTidIssueStatusesBodyCategory[keyof typeof PostApiV1TenantsTidIssueStatusesBodyCategory];


export const PostApiV1TenantsTidIssueStatusesBodyCategory = {
  unstarted: 'unstarted',
  started: 'started',
  done: 'done',
  closed: 'closed',
} as const;

export type PostApiV1TenantsTidIssueStatusesBody = {
  category?: PostApiV1TenantsTidIssueStatusesBodyCategory;
  color?: string;
  description?: string;
  icon?: string;
  key: string;
  name: string;
};

export type PostApiV1TenantsTidIssueStatuses200 = {
  resource: IssueStatus;
};

export type DeleteApiV1TenantsTidIssueStatusesSidBody = {
  /** @minimum 0 */
  version: number;
};

export type PutApiV1TenantsTidIssueStatusesSidBodyCategory = typeof PutApiV1TenantsTidIssueStatusesSidBodyCategory[keyof typeof PutApiV1TenantsTidIssueStatusesSidBodyCategory];


export const PutApiV1TenantsTidIssueStatusesSidBodyCategory = {
  unstarted: 'unstarted',
  started: 'started',
  done: 'done',
  closed: 'closed',
} as const;

export type PutApiV1TenantsTidIssueStatusesSidBody = {
  category?: PutApiV1TenantsTidIssueStatusesSidBodyCategory;
  color?: string;
  description?: string;
  icon?: string;
  name: string;
  position?: number;
  /** @minimum 0 */
  version?: number;
};

export type GetApiV1TenantsTidIssueViewsParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidIssueViews200 = {
  items: IssueView[];
  nextCursor: string;
};

export type PostApiV1TenantsTidIssueViewsBodyFilter = { [key: string]: unknown };

export type PostApiV1TenantsTidIssueViewsBody = {
  filter?: PostApiV1TenantsTidIssueViewsBodyFilter;
  name: string;
};

export type PostApiV1TenantsTidIssueViews200 = {
  resource: IssueView;
};

export type DeleteApiV1TenantsTidIssueViewsVidBody = {
  /** @minimum 0 */
  version: number;
};

export type PutApiV1TenantsTidIssueViewsVidBodyFilter = { [key: string]: unknown };

export type PutApiV1TenantsTidIssueViewsVidBody = {
  filter?: PutApiV1TenantsTidIssueViewsVidBodyFilter;
  name: string;
  /** @minimum 0 */
  version?: number;
};

export type GetApiV1TenantsTidIssues200 = {
  items: Issue[];
  nextCursor: string;
};

export type PostApiV1TenantsTidIssuesBodyAssigneeType = typeof PostApiV1TenantsTidIssuesBodyAssigneeType[keyof typeof PostApiV1TenantsTidIssuesBodyAssigneeType];


export const PostApiV1TenantsTidIssuesBodyAssigneeType = {
  user: 'user',
  agent: 'agent',
  team: 'team',
} as const;

export type PostApiV1TenantsTidIssuesBodyPriority = typeof PostApiV1TenantsTidIssuesBodyPriority[keyof typeof PostApiV1TenantsTidIssuesBodyPriority];


export const PostApiV1TenantsTidIssuesBodyPriority = {
  urgent: 'urgent',
  high: 'high',
  medium: 'medium',
  low: 'low',
  none: 'none',
} as const;

export type PostApiV1TenantsTidIssuesBodyProperties = { [key: string]: unknown };

export type PostApiV1TenantsTidIssuesBody = {
  assigneeId?: string;
  assigneeType?: PostApiV1TenantsTidIssuesBodyAssigneeType;
  assigneeUserId?: string;
  description?: string;
  parentIssueId?: string;
  priority?: PostApiV1TenantsTidIssuesBodyPriority;
  projectRef?: string;
  properties?: PostApiV1TenantsTidIssuesBodyProperties;
  /** @pattern ^[a-z0-9][a-z0-9_]{0,31}$ */
  status?: string;
  title: string;
};

export type PostApiV1TenantsTidIssues200 = {
  resource: Issue;
};

export type PostApiV1TenantsTidIssuesBatchBodyPriority = typeof PostApiV1TenantsTidIssuesBatchBodyPriority[keyof typeof PostApiV1TenantsTidIssuesBatchBodyPriority];


export const PostApiV1TenantsTidIssuesBatchBodyPriority = {
  urgent: 'urgent',
  high: 'high',
  medium: 'medium',
  low: 'low',
  none: 'none',
} as const;

export type PostApiV1TenantsTidIssuesBatchBody = {
  assigneeUserId?: string;
  ids: string[];
  priority?: PostApiV1TenantsTidIssuesBatchBodyPriority;
  /** @pattern ^[a-z0-9][a-z0-9_]{0,31}$ */
  status?: string;
};

export type PostApiV1TenantsTidIssuesBatch200 = {
  items: Issue[];
  nextCursor: string;
};

export type DeleteApiV1TenantsTidIssuesIidBody = {
  /** @minimum 0 */
  version: number;
};

export type PutApiV1TenantsTidIssuesIidBodyAssigneeType = typeof PutApiV1TenantsTidIssuesIidBodyAssigneeType[keyof typeof PutApiV1TenantsTidIssuesIidBodyAssigneeType];


export const PutApiV1TenantsTidIssuesIidBodyAssigneeType = {
  user: 'user',
  agent: 'agent',
  team: 'team',
} as const;

export type PutApiV1TenantsTidIssuesIidBodyPriority = typeof PutApiV1TenantsTidIssuesIidBodyPriority[keyof typeof PutApiV1TenantsTidIssuesIidBodyPriority];


export const PutApiV1TenantsTidIssuesIidBodyPriority = {
  urgent: 'urgent',
  high: 'high',
  medium: 'medium',
  low: 'low',
  none: 'none',
} as const;

export type PutApiV1TenantsTidIssuesIidBodyProperties = { [key: string]: unknown };

export type PutApiV1TenantsTidIssuesIidBody = {
  assigneeId?: string;
  assigneeType?: PutApiV1TenantsTidIssuesIidBodyAssigneeType;
  assigneeUserId?: string;
  description?: string;
  parentIssueId?: string;
  priority?: PutApiV1TenantsTidIssuesIidBodyPriority;
  projectRef?: string;
  properties?: PutApiV1TenantsTidIssuesIidBodyProperties;
  /** @pattern ^[a-z0-9][a-z0-9_]{0,31}$ */
  status?: string;
  title?: string;
  /** @minimum 0 */
  version?: number;
};

export type PostApiV1TenantsTidIssuesIidCollaborationAssistBodyValues = { [key: string]: unknown };

export type PostApiV1TenantsTidIssuesIidCollaborationAssistBody = {
  targetId: string;
  values?: PostApiV1TenantsTidIssuesIidCollaborationAssistBodyValues;
};

export type GetApiV1TenantsTidIssuesIidCommentsParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidIssuesIidComments200 = {
  items: Comment[];
  nextCursor: string;
};

export type PostApiV1TenantsTidIssuesIidCommentsBodyTargetsItemType = typeof PostApiV1TenantsTidIssuesIidCommentsBodyTargetsItemType[keyof typeof PostApiV1TenantsTidIssuesIidCommentsBodyTargetsItemType];


export const PostApiV1TenantsTidIssuesIidCommentsBodyTargetsItemType = {
  user: 'user',
  agent: 'agent',
  team: 'team',
  workflow: 'workflow',
} as const;

export type PostApiV1TenantsTidIssuesIidCommentsBodyTargetsItem = {
  id: string;
  task?: string;
  type: PostApiV1TenantsTidIssuesIidCommentsBodyTargetsItemType;
};

export type PostApiV1TenantsTidIssuesIidCommentsBody = {
  body: string;
  parentId?: string;
  targets?: PostApiV1TenantsTidIssuesIidCommentsBodyTargetsItem[];
};

export type PostApiV1TenantsTidIssuesIidComments200 = {
  resource: Comment;
};

export type DeleteApiV1TenantsTidIssuesIidCommentsCidBody = {
  /** @minimum 0 */
  version: number;
};

export type PutApiV1TenantsTidIssuesIidCommentsCidBody = {
  body: string;
  /** @minimum 0 */
  version?: number;
};

export type GetApiV1TenantsTidIssuesIidContextRefs200 = {
  items: ContextRef[];
  nextCursor: string;
};

export type PostApiV1TenantsTidIssuesIidContextRefsBodyRefType = typeof PostApiV1TenantsTidIssuesIidContextRefsBodyRefType[keyof typeof PostApiV1TenantsTidIssuesIidContextRefsBodyRefType];


export const PostApiV1TenantsTidIssuesIidContextRefsBodyRefType = {
  parent_issue: 'parent_issue',
  run: 'run',
  timeline_message: 'timeline_message',
  pull_request: 'pull_request',
  project: 'project',
  workspace: 'workspace',
  acceptance_criteria: 'acceptance_criteria',
} as const;

export type PostApiV1TenantsTidIssuesIidContextRefsBody = {
  refId: string;
  refType: PostApiV1TenantsTidIssuesIidContextRefsBodyRefType;
};

export type PostApiV1TenantsTidIssuesIidContextRefs200 = {
  resource: ContextRef;
};

export type DeleteApiV1TenantsTidIssuesIidContextRefsCridBody = { [key: string]: unknown };

export type GetApiV1TenantsTidIssuesIidInteractions200 = {
  items: IssueInteraction[];
  nextCursor: string;
};

export type PostApiV1TenantsTidIssuesIidInteractionsIxidConfirmBodyValues = { [key: string]: unknown };

export type PostApiV1TenantsTidIssuesIidInteractionsIxidConfirmBody = {
  contextRefs?: ContextRefRef[];
  values: PostApiV1TenantsTidIssuesIidInteractionsIxidConfirmBodyValues;
};

export type PostApiV1TenantsTidIssuesIidInteractionsIxidConfirm200 = {
  resource: IssueRun;
};

export type GetApiV1TenantsTidIssuesIidLabelsParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidIssuesIidLabels200 = {
  items: Label[];
  nextCursor: string;
};

export type PostApiV1TenantsTidIssuesIidLabelsBody = {
  labelId: string;
};

export type PostApiV1TenantsTidIssuesIidLabels200 = {
  resource: Label;
};

export type DeleteApiV1TenantsTidIssuesIidLabelsLidBody = { [key: string]: unknown };

export type PostApiV1TenantsTidIssuesIidMoveBody = {
  afterId?: string;
  beforeId?: string;
  /** @pattern ^[a-z0-9][a-z0-9_]{0,31}$ */
  status?: string;
  /** @minimum 0 */
  version: number;
};

export type GetApiV1TenantsTidIssuesIidRunsParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidIssuesIidRuns200 = {
  items: IssueRun[];
  nextCursor: string;
};

export type PostApiV1TenantsTidIssuesIidRunsBodyExecutorType = typeof PostApiV1TenantsTidIssuesIidRunsBodyExecutorType[keyof typeof PostApiV1TenantsTidIssuesIidRunsBodyExecutorType];


export const PostApiV1TenantsTidIssuesIidRunsBodyExecutorType = {
  agent: 'agent',
  team: 'team',
  workflow: 'workflow',
} as const;

export type PostApiV1TenantsTidIssuesIidRunsBodyInput = { [key: string]: unknown };

export type PostApiV1TenantsTidIssuesIidRunsBody = {
  executorId: string;
  executorType: PostApiV1TenantsTidIssuesIidRunsBodyExecutorType;
  input?: PostApiV1TenantsTidIssuesIidRunsBodyInput;
};

export type PostApiV1TenantsTidIssuesIidRuns200 = {
  resource: IssueRun;
};

export type GetApiV1TenantsTidIssuesIidRunsRidThreadParams = {
/**
 * @minimum 1
 * @maximum 500
 */
limit?: number;
/**
 * Forward Thread seq cursor: the window starts after this seq. Mutually exclusive with before; neither cursor reads the tail.
 * @minimum 0
 */
after?: number;
/**
 * Backward Thread seq cursor: the window ends just before this seq, taking the entries closest to it from below. Mutually exclusive with after.
 * @minimum 0
 */
before?: number;
};

export type GetApiV1TenantsTidIssuesIidRunsRidThread200ThreadState = typeof GetApiV1TenantsTidIssuesIidRunsRidThread200ThreadState[keyof typeof GetApiV1TenantsTidIssuesIidRunsRidThread200ThreadState];


export const GetApiV1TenantsTidIssuesIidRunsRidThread200ThreadState = {
  pending: 'pending',
  active: 'active',
  idle: 'idle',
  ending: 'ending',
  ended: 'ended',
} as const;

export type GetApiV1TenantsTidIssuesIidRunsRidThread200 = {
  canAppend: boolean;
  canEnd: boolean;
  /** @nullable */
  failureCode?: string | null;
  /**
     * When the Thread became idle; null in every other state.
     * @nullable
     */
  idleSince: string | null;
  /** @nullable */
  initiatorUserId: string | null;
  items: ThreadEntry[];
  model: ThreadModel | null;
  /**
     * The window's last seq, to be sent back as `after`. Null for an empty window.
     * @nullable
     */
  nextCursor: number | null;
  /**
     * The window's first seq, to be sent back as `before`. Null for an empty window.
     * @nullable
     */
  prevCursor: number | null;
  threadState: GetApiV1TenantsTidIssuesIidRunsRidThread200ThreadState;
};

export type PostApiV1TenantsTidIssuesIidRunsRidThreadEndBody = { [key: string]: unknown };

export type PostApiV1TenantsTidIssuesIidRunsRidThreadEnd202ThreadState = typeof PostApiV1TenantsTidIssuesIidRunsRidThreadEnd202ThreadState[keyof typeof PostApiV1TenantsTidIssuesIidRunsRidThreadEnd202ThreadState];


export const PostApiV1TenantsTidIssuesIidRunsRidThreadEnd202ThreadState = {
  ending: 'ending',
} as const;

export type PostApiV1TenantsTidIssuesIidRunsRidThreadEnd202 = {
  threadState: PostApiV1TenantsTidIssuesIidRunsRidThreadEnd202ThreadState;
};

export type PostApiV1TenantsTidIssuesIidRunsRidThreadMessagesBodyContentItemType = typeof PostApiV1TenantsTidIssuesIidRunsRidThreadMessagesBodyContentItemType[keyof typeof PostApiV1TenantsTidIssuesIidRunsRidThreadMessagesBodyContentItemType];


export const PostApiV1TenantsTidIssuesIidRunsRidThreadMessagesBodyContentItemType = {
  text: 'text',
} as const;

export type PostApiV1TenantsTidIssuesIidRunsRidThreadMessagesBodyContentItem = {
  text: string;
  type: PostApiV1TenantsTidIssuesIidRunsRidThreadMessagesBodyContentItemType;
};

export type PostApiV1TenantsTidIssuesIidRunsRidThreadMessagesBody = {
  content: PostApiV1TenantsTidIssuesIidRunsRidThreadMessagesBodyContentItem[];
};

export type PostApiV1TenantsTidIssuesIidRunsRidThreadMessages201 = {
  resource: ThreadEntry;
};

export type DeleteApiV1TenantsTidIssuesIidSubscribersBody = {
  userId: string;
};

export type DeleteApiV1TenantsTidIssuesIidSubscribers200 = {
  resource: User;
};

export type GetApiV1TenantsTidIssuesIidSubscribersParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidIssuesIidSubscribers200 = {
  items: User[];
  nextCursor: string;
};

export type PostApiV1TenantsTidIssuesIidSubscribersBody = {
  userId: string;
};

export type PostApiV1TenantsTidIssuesIidSubscribers200 = {
  resource: User;
};

export type GetApiV1TenantsTidIssuesIidTimeline200 = {
  items: TimelineEntry[];
  nextCursor: string;
};

export type GetApiV1TenantsTidJoinLinksParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidJoinLinks200 = {
  items: JoinLink[];
  nextCursor: string;
};

export type PostApiV1TenantsTidJoinLinksBody = {
  token: string;
};

export type DeleteApiV1TenantsTidJoinLinksLidBody = {
  /** @minimum 0 */
  version: number;
};

export type GetApiV1TenantsTidJoinRequestsParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidJoinRequests200 = {
  items: JoinRequest[];
  nextCursor: string;
};

export type PostApiV1TenantsTidJoinRequestsRidApproveBody = {
  /** @minimum 0 */
  version: number;
};

export type PostApiV1TenantsTidJoinRequestsRidRejectBody = {
  /** @minimum 0 */
  version: number;
};

export type GetApiV1TenantsTidLabelsParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidLabels200 = {
  items: Label[];
  nextCursor: string;
};

export type PostApiV1TenantsTidLabelsBody = {
  color?: string;
  name: string;
};

export type PostApiV1TenantsTidLabels200 = {
  resource: Label;
};

export type DeleteApiV1TenantsTidLabelsLidBody = {
  /** @minimum 0 */
  version: number;
};

export type PutApiV1TenantsTidLabelsLidBody = {
  color?: string;
  name: string;
  /** @minimum 0 */
  version?: number;
};

export type GetApiV1TenantsTidMembersParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidMembers200 = {
  items: MemberListItem[];
  nextCursor: string;
};

export type PostApiV1TenantsTidMembersHuaweiBodyRole = typeof PostApiV1TenantsTidMembersHuaweiBodyRole[keyof typeof PostApiV1TenantsTidMembersHuaweiBodyRole];


export const PostApiV1TenantsTidMembersHuaweiBodyRole = {
  admin: 'admin',
  member: 'member',
} as const;

export type PostApiV1TenantsTidMembersHuaweiBody = {
  globalUserId: string;
  keyword: string;
  role?: PostApiV1TenantsTidMembersHuaweiBodyRole;
};

export type PutApiV1TenantsTidMembersUidBodyRole = typeof PutApiV1TenantsTidMembersUidBodyRole[keyof typeof PutApiV1TenantsTidMembersUidBodyRole];


export const PutApiV1TenantsTidMembersUidBodyRole = {
  admin: 'admin',
  member: 'member',
} as const;

export type PutApiV1TenantsTidMembersUidBodyStatus = typeof PutApiV1TenantsTidMembersUidBodyStatus[keyof typeof PutApiV1TenantsTidMembersUidBodyStatus];


export const PutApiV1TenantsTidMembersUidBodyStatus = {
  active: 'active',
  disabled: 'disabled',
} as const;

export type PutApiV1TenantsTidMembersUidBody = {
  role: PutApiV1TenantsTidMembersUidBodyRole;
  status: PutApiV1TenantsTidMembersUidBodyStatus;
  /** @minimum 0 */
  version?: number;
};

export type PostApiV1TenantsTidOperationsOidRetryBody = {
  /** @minimum 0 */
  version: number;
};

export type PostApiV1TenantsTidOperationsOidRetry202 = {
  operation: Operation | AdminOperation;
};

export type GetApiV1TenantsTidPeopleParams = {
/**
 * @minLength 2
 * @maxLength 100
 */
keyword: string;
};

export type GetApiV1TenantsTidPeople200 = {
  items: DirectoryPerson[];
};

export type GetApiV1TenantsTidProjectsParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidProjects200 = {
  items: Project[];
  nextCursor: string;
};

export type PostApiV1TenantsTidProjectsBody = {
  credentialRefId?: string;
  defaultBranch: string;
  name: string;
  repositoryUrl: string;
};

export type PostApiV1TenantsTidProjects202 = {
  operation: Operation;
  resource: Project;
  workspace: Workspace;
};

export type DeleteApiV1TenantsTidProjectsPidBody = {
  /** @minimum 0 */
  version: number;
};

export type DeleteApiV1TenantsTidProjectsPid202 = {
  operation: Operation;
  resource: Project;
};

export type PatchApiV1TenantsTidProjectsPidBody = {
  name: string;
  /** @minimum 0 */
  version: number;
};

export type GetApiV1TenantsTidProjectsPidWorkspacesParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidProjectsPidWorkspaces200 = {
  items: WorkspaceListItem[];
  nextCursor: string;
};

export type PostApiV1TenantsTidProjectsPidWorkspacesBody = {
  baseRef: string;
  title: string;
};

export type PostApiV1TenantsTidProjectsPidWorkspaces202 = {
  operation: Operation;
  resource: Workspace;
};

export type GetApiV1TenantsTidResourceStatusParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidResourceStatus200 = {
  items: AdminResource[];
  nextCursor: string;
};

export type GetApiV1TenantsTidSpacesParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidSpaces200 = {
  items: SpaceListItem[];
  nextCursor: string;
};

export type PatchApiV1TenantsTidSpacesSpaceIdBody = {
  description?: string;
  name: string;
  /** @minimum 0 */
  version: number;
};

export type DeleteApiV1TenantsTidSpacesSpaceIdPluginsBody = {
  identifier: string;
  /** @minimum 0 */
  version: number;
};

export type DeleteApiV1TenantsTidSpacesSpaceIdPlugins200 = {
  resource: SpacePlugin;
};

export type PostApiV1TenantsTidSpacesSpaceIdPluginsBody = {
  identifier: string;
  pluginVersion?: string;
  /** @minimum 0 */
  version?: number;
};

export type PostApiV1TenantsTidSpacesSpaceIdPlugins200 = {
  resource: SpacePlugin;
};

export type GetApiV1TenantsTidSpacesSpaceIdProjectsParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidSpacesSpaceIdProjects200 = {
  items: Project[];
  nextCursor: string;
};

export type PostApiV1TenantsTidSpacesSpaceIdProjectsBody = {
  credentialRefId?: string;
  defaultBranch: string;
  name: string;
  repositoryUrl: string;
};

export type PostApiV1TenantsTidSpacesSpaceIdProjects202 = {
  operation: Operation;
  resource: Project;
  workspace: Workspace;
};

export type GetApiV1TenantsTidWorkflowsParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidWorkflows200 = {
  items: Workflow[];
  nextCursor: string;
};

export type PostApiV1TenantsTidWorkflowsBodyGraph = { [key: string]: unknown };

export type PostApiV1TenantsTidWorkflowsBody = {
  description?: string;
  graph?: PostApiV1TenantsTidWorkflowsBodyGraph;
  name: string;
};

export type PostApiV1TenantsTidWorkflows200 = {
  resource: Workflow;
};

export type DeleteApiV1TenantsTidWorkflowsWfidBody = {
  /** @minimum 0 */
  version: number;
};

export type PutApiV1TenantsTidWorkflowsWfidBodyGraph = { [key: string]: unknown };

export type PutApiV1TenantsTidWorkflowsWfidBody = {
  description?: string;
  graph?: PutApiV1TenantsTidWorkflowsWfidBodyGraph;
  name: string;
  /** @minimum 0 */
  version?: number;
};

export type PostApiV1TenantsTidWorkflowsWfidPublishBody = {
  name?: string;
};

export type PostApiV1TenantsTidWorkflowsWfidPublish200 = {
  resource: WorkflowSnapshot;
};

export type GetApiV1TenantsTidWorkflowsWfidRunsParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidWorkflowsWfidRuns200 = {
  items: WorkflowRun[];
  nextCursor: string;
};

export type PostApiV1TenantsTidWorkflowsWfidRunsBodyInput = { [key: string]: unknown };

export type PostApiV1TenantsTidWorkflowsWfidRunsBody = {
  input?: PostApiV1TenantsTidWorkflowsWfidRunsBodyInput;
  name?: string;
  snapshotId?: string;
};

export type PostApiV1TenantsTidWorkflowsWfidRuns200 = {
  resource: WorkflowRun;
};

export type GetApiV1TenantsTidWorkflowsWfidSnapshotsParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidWorkflowsWfidSnapshots200 = {
  items: WorkflowSnapshot[];
  nextCursor: string;
};

export type PutApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestoreBody = {
  /** @minimum 0 */
  version?: number;
};

export type DeleteApiV1TenantsTidWorkspacesWidBody = {
  sessionId: string;
  /** @minimum 0 */
  version: number;
};

export type DeleteApiV1TenantsTidWorkspacesWid202 = {
  operation: Operation;
  resource: Workspace;
};

export type PostApiV1TenantsTidWorkspacesWidControlAcquireBody = {
  /** @minimum 0 */
  version: number;
};

export type PostApiV1TenantsTidWorkspacesWidControlReleaseBody = {
  sessionId: string;
  /** @minimum 0 */
  version: number;
};

export type PostApiV1TenantsTidWorkspacesWidControlRenewBody = {
  sessionId: string;
  /** @minimum 0 */
  version: number;
};

export type GetApiV1TenantsTidWorkspacesWidForceStop200 = {
  forceStop: RuntimeForceStop | null;
};

export type PostApiV1TenantsTidWorkspacesWidForceStopBody = {
  impactConfirmed: boolean;
  reason: string;
  /** @minimum 0 */
  version: number;
};

export type PostApiV1TenantsTidWorkspacesWidForceStop202 = {
  forceStop: RuntimeForceStop;
  resource: AdminResource;
};

export type PostApiV1TenantsTidWorkspacesWidRestartBody = {
  sessionId: string;
  /** @minimum 0 */
  version: number;
};

export type PostApiV1TenantsTidWorkspacesWidRestart202 = {
  operation: Operation;
  resource: Workspace;
};

export type PostApiV1TenantsTidWorkspacesWidStartBody = {
  sessionId: string;
  /** @minimum 0 */
  version: number;
};

export type PostApiV1TenantsTidWorkspacesWidStart202 = {
  operation: Operation;
  resource: Workspace;
};

export type PostApiV1TenantsTidWorkspacesWidStopBody = {
  sessionId: string;
  /** @minimum 0 */
  version: number;
};

export type PostApiV1TenantsTidWorkspacesWidStop202 = {
  operation: Operation;
  resource: Workspace;
};

export type Health200DependenciesObjectStore = typeof Health200DependenciesObjectStore[keyof typeof Health200DependenciesObjectStore];


export const Health200DependenciesObjectStore = {
  configured: 'configured',
  unconfigured: 'unconfigured',
} as const;

export type Health200Dependencies = {
  objectStore: Health200DependenciesObjectStore;
};

export type Health200Status = typeof Health200Status[keyof typeof Health200Status];


export const Health200Status = {
  ok: 'ok',
} as const;

export type Health200 = {
  dependencies?: Health200Dependencies;
  status: Health200Status;
};

export type PostInternalV1AccessBodyAction = typeof PostInternalV1AccessBodyAction[keyof typeof PostInternalV1AccessBodyAction];


export const PostInternalV1AccessBodyAction = {
  read: 'read',
  execute: 'execute',
} as const;

export type PostInternalV1AccessBody = {
  action: PostInternalV1AccessBodyAction;
  /** @minimum 0 */
  epoch?: number;
  sessionId: string;
  tenantId: string;
  workspaceId: string;
};

export type PostInternalV1AdmissionsBodyAction = typeof PostInternalV1AdmissionsBodyAction[keyof typeof PostInternalV1AdmissionsBodyAction];


export const PostInternalV1AdmissionsBodyAction = {
  read: 'read',
  execute: 'execute',
} as const;

export type PostInternalV1AdmissionsBodyKind = typeof PostInternalV1AdmissionsBodyKind[keyof typeof PostInternalV1AdmissionsBodyKind];


export const PostInternalV1AdmissionsBodyKind = {
  task: 'task',
  interaction: 'interaction',
} as const;

export type PostInternalV1AdmissionsBody = {
  action: PostInternalV1AdmissionsBodyAction;
  /** @minimum 0 */
  epoch: number;
  kind: PostInternalV1AdmissionsBodyKind;
  sessionId: string;
  tenantId: string;
  ticketId: string;
  workspaceId: string;
};

export type PostInternalV1ControllerLeaseAcquireBody = { [key: string]: unknown };

export type PostInternalV1ControllerLeaseReleaseBody = {
  /** @minimum 0 */
  epoch: number;
};

export type PostInternalV1ControllerLeaseRenewBody = {
  /** @minimum 0 */
  epoch: number;
};

export type PostInternalV1NodesIdleBody = {
  /** @minimum 0 */
  admissionEpoch: number;
  idle: boolean;
  operationId: string;
  /** @minimum 0 */
  version: number;
};

export type PostInternalV1NodesRegisterBodyProtocolVersion = typeof PostInternalV1NodesRegisterBodyProtocolVersion[keyof typeof PostInternalV1NodesRegisterBodyProtocolVersion];


export const PostInternalV1NodesRegisterBodyProtocolVersion = {
  NUMBER_1: 1,
} as const;

export type PostInternalV1NodesRegisterBody = {
  protocolVersion: PostInternalV1NodesRegisterBodyProtocolVersion;
};

export type PostInternalV1NodesStatusBodyConnectionState = typeof PostInternalV1NodesStatusBodyConnectionState[keyof typeof PostInternalV1NodesStatusBodyConnectionState];


export const PostInternalV1NodesStatusBodyConnectionState = {
  connected: 'connected',
  disconnected: 'disconnected',
} as const;

export type PostInternalV1NodesStatusBody = {
  connectionState: PostInternalV1NodesStatusBodyConnectionState;
  initialized: boolean;
  /** @minimum 0 */
  version: number;
};

export type PostInternalV1NodesTicketsTicketFinishBody = {
  /** @minimum 0 */
  version: number;
};

export type PostInternalV1OperationsClaimBody = {
  /** @minimum 0 */
  epoch: number;
};

export type PostInternalV1OperationsOidAdvanceBody = {
  /** @minimum 0 */
  epoch: number;
  /** @minimum 0 */
  version: number;
};

export type PostInternalV1OperationsOidDeferBodyErrorCode = typeof PostInternalV1OperationsOidDeferBodyErrorCode[keyof typeof PostInternalV1OperationsOidDeferBodyErrorCode];


export const PostInternalV1OperationsOidDeferBodyErrorCode = {
  substrate_timeout: 'substrate_timeout',
  termination_unconfirmed: 'termination_unconfirmed',
  git_cleanup_failed: 'git_cleanup_failed',
  node_unavailable: 'node_unavailable',
  external_failure: 'external_failure',
  clone_failed: 'clone_failed',
  clone_result_unknown: 'clone_result_unknown',
  plugin_execution_failed: 'plugin_execution_failed',
  plugin_result_unknown: 'plugin_result_unknown',
} as const;

export type PostInternalV1OperationsOidDeferBodyState = typeof PostInternalV1OperationsOidDeferBodyState[keyof typeof PostInternalV1OperationsOidDeferBodyState];


export const PostInternalV1OperationsOidDeferBodyState = {
  blocked: 'blocked',
  retry_wait: 'retry_wait',
} as const;

export type PostInternalV1OperationsOidDeferBody = {
  /** @minimum 0 */
  epoch: number;
  errorCode: PostInternalV1OperationsOidDeferBodyErrorCode;
  /**
     * @minimum 1
     * @maximum 3600
     */
  retrySeconds: number;
  state: PostInternalV1OperationsOidDeferBodyState;
  /** @minimum 0 */
  version: number;
};

export type PostInternalV1OperationsOidEffectsBodyKind = typeof PostInternalV1OperationsOidEffectsBodyKind[keyof typeof PostInternalV1OperationsOidEffectsBodyKind];


export const PostInternalV1OperationsOidEffectsBodyKind = {
  sandbox_ensure: 'sandbox_ensure',
  sandbox_terminate: 'sandbox_terminate',
  workspace_data_delete: 'workspace_data_delete',
  plugin_ensure: 'plugin_ensure',
  plugin_delete: 'plugin_delete',
} as const;

export type PostInternalV1OperationsOidEffectsBody = {
  /** @minimum 0 */
  epoch: number;
  kind: PostInternalV1OperationsOidEffectsBodyKind;
  /** @minimum 0 */
  version: number;
  workspaceId?: string;
};

export type PostInternalV1OperationsOidEffects200 = {
  effect: Effect;
  operation: Operation;
};

export type PostInternalV1OperationsOidEffectsEidResultBodyState = typeof PostInternalV1OperationsOidEffectsEidResultBodyState[keyof typeof PostInternalV1OperationsOidEffectsEidResultBodyState];


export const PostInternalV1OperationsOidEffectsEidResultBodyState = {
  running: 'running',
  succeeded: 'succeeded',
  failed: 'failed',
  absent: 'absent',
} as const;

export type PostInternalV1OperationsOidEffectsEidResultBody = {
  /** @minimum 0 */
  epoch: number;
  externalId?: string;
  result: EffectResult;
  state: PostInternalV1OperationsOidEffectsEidResultBodyState;
  /** @minimum 0 */
  version: number;
};

export type PostInternalV1OperationsOidEffectsEidResult200 = {
  effect: Effect;
  operation: Operation;
};

export type PostInternalV1OperationsOidSnapshotBody = {
  /** @minimum 0 */
  epoch: number;
  /** @minimum 0 */
  version: number;
};

