/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Error,
  GetApiV1TenantsTidSpaces200,
  GetApiV1TenantsTidSpacesParams,
  GetApiV1TenantsTidSpacesSpaceIdProjects200,
  GetApiV1TenantsTidSpacesSpaceIdProjectsParams,
  PatchApiV1TenantsTidSpacesSpaceIdBody,
  PostApiV1TenantsTidSpacesSpaceIdProjects202,
  PostApiV1TenantsTidSpacesSpaceIdProjectsBody,
  Space,
  SpaceEvent
} from '../generated.schemas';

import { customInstance } from '../../lib/api-client';
import type { ErrorType } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup; project and runtime access is shared within that tenant. Every tenant has one collaboration space. Active tenant members can read it. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/spaces
 */
export const getApiV1TenantsTidSpaces = (
    tid: string,
    params?: GetApiV1TenantsTidSpacesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetApiV1TenantsTidSpaces200>(
      {url: `/api/v1/tenants/${tid}/spaces`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiV1TenantsTidSpacesQueryKey = (tid: string,
    params?: GetApiV1TenantsTidSpacesParams,) => {
    return [
    `/api/v1/tenants/${tid}/spaces`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1TenantsTidSpacesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>, TError = ErrorType<Error>>(tid: string,
    params?: GetApiV1TenantsTidSpacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidSpacesQueryKey(tid,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>> = ({ signal }) => getApiV1TenantsTidSpaces(tid,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidSpacesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>>
export type GetApiV1TenantsTidSpacesQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidSpaces<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>, TError = ErrorType<Error>>(
 tid: string,
    params: undefined |  GetApiV1TenantsTidSpacesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpaces<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>, TError = ErrorType<Error>>(
 tid: string,
    params?: GetApiV1TenantsTidSpacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpaces<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>, TError = ErrorType<Error>>(
 tid: string,
    params?: GetApiV1TenantsTidSpacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/spaces
 */

export function useGetApiV1TenantsTidSpaces<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>, TError = ErrorType<Error>>(
 tid: string,
    params?: GetApiV1TenantsTidSpacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidSpacesQueryOptions(tid,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup; project and runtime access is shared within that tenant. Every tenant has one collaboration space. Active tenant members can read it. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/spaces/:spaceId
 */
export const getApiV1TenantsTidSpacesSpaceId = (
    tid: string,
    spaceId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Space>(
      {url: `/api/v1/tenants/${tid}/spaces/${spaceId}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV1TenantsTidSpacesSpaceIdQueryKey = (tid: string,
    spaceId: string,) => {
    return [
    `/api/v1/tenants/${tid}/spaces/${spaceId}`
    ] as const;
    }


export const getGetApiV1TenantsTidSpacesSpaceIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceId>>, TError = ErrorType<Error>>(tid: string,
    spaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidSpacesSpaceIdQueryKey(tid,spaceId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceId>>> = ({ signal }) => getApiV1TenantsTidSpacesSpaceId(tid,spaceId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && spaceId !== null && spaceId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidSpacesSpaceIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceId>>>
export type GetApiV1TenantsTidSpacesSpaceIdQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidSpacesSpaceId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceId>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpacesSpaceId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceId>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpacesSpaceId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceId>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/spaces/:spaceId
 */

export function useGetApiV1TenantsTidSpacesSpaceId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceId>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidSpacesSpaceIdQueryOptions(tid,spaceId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup; project and runtime access is shared within that tenant. Name and description may change; tenant and space names update together. Slug is immutable. Requires tenant admin and a matching version. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary PATCH /api/v1/tenants/:tid/spaces/:spaceId
 */
export const patchApiV1TenantsTidSpacesSpaceId = (
    tid: string,
    spaceId: string,
    patchApiV1TenantsTidSpacesSpaceIdBody: PatchApiV1TenantsTidSpacesSpaceIdBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Space>(
      {url: `/api/v1/tenants/${tid}/spaces/${spaceId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchApiV1TenantsTidSpacesSpaceIdBody, signal
    },
      options);
    }




export const getPatchApiV1TenantsTidSpacesSpaceIdMutationKey = () => ['patchApiV1TenantsTidSpacesSpaceId'] as const;

export const getPatchApiV1TenantsTidSpacesSpaceIdMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1TenantsTidSpacesSpaceId>>, TError,PatchApiV1TenantsTidSpacesSpaceIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1TenantsTidSpacesSpaceId>>, TError,PatchApiV1TenantsTidSpacesSpaceIdMutationVariables, TContext> => {

const mutationKey = getPatchApiV1TenantsTidSpacesSpaceIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1TenantsTidSpacesSpaceId>>, PatchApiV1TenantsTidSpacesSpaceIdMutationVariables> = (props) => {
          const {tid,spaceId,data} = props ?? {};

          return  patchApiV1TenantsTidSpacesSpaceId(tid,spaceId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1TenantsTidSpacesSpaceIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1TenantsTidSpacesSpaceId>>>
    export type PatchApiV1TenantsTidSpacesSpaceIdMutationBody = PatchApiV1TenantsTidSpacesSpaceIdBody
    export type PatchApiV1TenantsTidSpacesSpaceIdMutationError = ErrorType<Error>
    export type PatchApiV1TenantsTidSpacesSpaceIdMutationVariables = {tid: string;spaceId: string;data: PatchApiV1TenantsTidSpacesSpaceIdBody}

    /**
 * @summary PATCH /api/v1/tenants/:tid/spaces/:spaceId
 */
export const usePatchApiV1TenantsTidSpacesSpaceId = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1TenantsTidSpacesSpaceId>>, TError,PatchApiV1TenantsTidSpacesSpaceIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1TenantsTidSpacesSpaceId>>,
        TError,
        PatchApiV1TenantsTidSpacesSpaceIdMutationVariables,
        TContext
      > => {
      return useMutation(getPatchApiV1TenantsTidSpacesSpaceIdMutationOptions(options), queryClient);
    }
    /**
 * Membership is verified before the stream opens. Events are lightweight invalidation notices published after commit; clients refetch authoritative state over REST.
 * @summary Stream collaboration space events over server-sent events
 */
export const getSpaceEvents = (
    tid: string,
    spaceId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<SpaceEvent>(
      {url: `/api/v1/tenants/${tid}/spaces/${spaceId}/events`, method: 'GET', signal
    },
      options);
    }




export const getGetSpaceEventsQueryKey = (tid: string,
    spaceId: string,) => {
    return [
    `/api/v1/tenants/${tid}/spaces/${spaceId}/events`
    ] as const;
    }


export const getGetSpaceEventsQueryOptions = <TData = Awaited<ReturnType<typeof getSpaceEvents>>, TError = ErrorType<Error>>(tid: string,
    spaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpaceEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSpaceEventsQueryKey(tid,spaceId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSpaceEvents>>> = ({ signal }) => getSpaceEvents(tid,spaceId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && spaceId !== null && spaceId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSpaceEvents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSpaceEventsQueryResult = NonNullable<Awaited<ReturnType<typeof getSpaceEvents>>>
export type GetSpaceEventsQueryError = ErrorType<Error>


export function useGetSpaceEvents<TData = Awaited<ReturnType<typeof getSpaceEvents>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpaceEvents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSpaceEvents>>,
          TError,
          Awaited<ReturnType<typeof getSpaceEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSpaceEvents<TData = Awaited<ReturnType<typeof getSpaceEvents>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpaceEvents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSpaceEvents>>,
          TError,
          Awaited<ReturnType<typeof getSpaceEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSpaceEvents<TData = Awaited<ReturnType<typeof getSpaceEvents>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpaceEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Stream collaboration space events over server-sent events
 */

export function useGetSpaceEvents<TData = Awaited<ReturnType<typeof getSpaceEvents>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpaceEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSpaceEventsQueryOptions(tid,spaceId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup; project and runtime access is shared within that tenant. Project collection scoped to the tenant's sole collaboration space; active tenant membership is required. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/spaces/:spaceId/projects
 */
export const getApiV1TenantsTidSpacesSpaceIdProjects = (
    tid: string,
    spaceId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdProjectsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetApiV1TenantsTidSpacesSpaceIdProjects200>(
      {url: `/api/v1/tenants/${tid}/spaces/${spaceId}/projects`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiV1TenantsTidSpacesSpaceIdProjectsQueryKey = (tid: string,
    spaceId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdProjectsParams,) => {
    return [
    `/api/v1/tenants/${tid}/spaces/${spaceId}/projects`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1TenantsTidSpacesSpaceIdProjectsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdProjects>>, TError = ErrorType<Error>>(tid: string,
    spaceId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdProjects>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidSpacesSpaceIdProjectsQueryKey(tid,spaceId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdProjects>>> = ({ signal }) => getApiV1TenantsTidSpacesSpaceIdProjects(tid,spaceId,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && spaceId !== null && spaceId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdProjects>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidSpacesSpaceIdProjectsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdProjects>>>
export type GetApiV1TenantsTidSpacesSpaceIdProjectsQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidSpacesSpaceIdProjects<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdProjects>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    params: undefined |  GetApiV1TenantsTidSpacesSpaceIdProjectsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdProjects>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdProjects>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpacesSpaceIdProjects<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdProjects>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdProjects>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdProjects>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpacesSpaceIdProjects<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdProjects>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdProjects>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/spaces/:spaceId/projects
 */

export function useGetApiV1TenantsTidSpacesSpaceIdProjects<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdProjects>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdProjects>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidSpacesSpaceIdProjectsQueryOptions(tid,spaceId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup; project and runtime access is shared within that tenant. Project collection scoped to the tenant's sole collaboration space; active tenant membership is required. Creates Project/storage/main Workspace/operation atomically in the tenant's sole collaboration space. repositoryUrl allows HTTPS or SSH with no password/query/fragment. defaultBranch defaults to HEAD; credentialRefId must belong to tenant and owner. Storage/worktree/sandbox initialization is asynchronous. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary POST /api/v1/tenants/:tid/spaces/:spaceId/projects
 */
export const postApiV1TenantsTidSpacesSpaceIdProjects = (
    tid: string,
    spaceId: string,
    postApiV1TenantsTidSpacesSpaceIdProjectsBody: PostApiV1TenantsTidSpacesSpaceIdProjectsBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostApiV1TenantsTidSpacesSpaceIdProjects202>(
      {url: `/api/v1/tenants/${tid}/spaces/${spaceId}/projects`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1TenantsTidSpacesSpaceIdProjectsBody, signal
    },
      options);
    }




export const getPostApiV1TenantsTidSpacesSpaceIdProjectsMutationKey = () => ['postApiV1TenantsTidSpacesSpaceIdProjects'] as const;

export const getPostApiV1TenantsTidSpacesSpaceIdProjectsMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdProjects>>, TError,PostApiV1TenantsTidSpacesSpaceIdProjectsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdProjects>>, TError,PostApiV1TenantsTidSpacesSpaceIdProjectsMutationVariables, TContext> => {

const mutationKey = getPostApiV1TenantsTidSpacesSpaceIdProjectsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdProjects>>, PostApiV1TenantsTidSpacesSpaceIdProjectsMutationVariables> = (props) => {
          const {tid,spaceId,data} = props ?? {};

          return  postApiV1TenantsTidSpacesSpaceIdProjects(tid,spaceId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TenantsTidSpacesSpaceIdProjectsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdProjects>>>
    export type PostApiV1TenantsTidSpacesSpaceIdProjectsMutationBody = PostApiV1TenantsTidSpacesSpaceIdProjectsBody
    export type PostApiV1TenantsTidSpacesSpaceIdProjectsMutationError = ErrorType<Error>
    export type PostApiV1TenantsTidSpacesSpaceIdProjectsMutationVariables = {tid: string;spaceId: string;data: PostApiV1TenantsTidSpacesSpaceIdProjectsBody}

    /**
 * @summary POST /api/v1/tenants/:tid/spaces/:spaceId/projects
 */
export const usePostApiV1TenantsTidSpacesSpaceIdProjects = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdProjects>>, TError,PostApiV1TenantsTidSpacesSpaceIdProjectsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdProjects>>,
        TError,
        PostApiV1TenantsTidSpacesSpaceIdProjectsMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV1TenantsTidSpacesSpaceIdProjectsMutationOptions(options), queryClient);
    }
